/* exported bdcStateBits, startupState, relaysState */

var bdcStateBits = [
	"None",
    "_obsolete_EVENT_ID_BRK_UnknownErrorReason",
    "_obsolete_EVENT_ID_BRK_Undervoltage",
    "_obsolete_EVENT_ID_BRK_PDP",
    "V_LV_IN_too_Low",
    "V_LV_IN_too_High",
    "I_LV_too_High",
    "DeviceOverTemperature",
    "V_HV_too_High",
    "Rampup_V_HV_failure",
    "reserved_10",
    "Pwm_Limited",
    "Fan_failure",
    "PowerStageShuttedDown",
    "PowerLimitedThermalDerating",
    "StillNotStartedNoError",
    "StartingUp",
    "StillNotStartedError",
    "PowerControlled",
    "PowerLimitedToMaximum",
    "PowerLimitedFanFault",
    "BatteryEndOfChargeVoltage",
    "BatteryDeepDischargeProtection",
    "BatteryChargeCurrentLimit",
    "BatteryDischargeCurrentLimit",
    "HVminimumVoltageLimit",
    "HVmaximumVoltageLimit",
    "ChargeCircuitInterruption",
    "CommunicationWatchdogExpired",
    "PotFreeContact_UbatTopExeeded",
    "PotFreeContact_UbatBottomExeeded",
    "BDC_is_not_Running",
    "VersionWrongHardware",
    "SupplyOutOfRange3V3",
    "12V_Supply_or_12V_Load_Error",
    "HWprotect_OV_LV",
    "HWprotect_OV_AC",
    "HWprotect_OV_HV1",
    "HWprotect_OC_HV",
    "HWprotect_OC_LV",
    "HWprotect_DISABLE_1",
    "SensorDefectNTC_TEST",
    "SensorDefectNTC_T4",
    "SensorDefectNTC_TR",
    "SensorDefectNTC_L",
    "SensorDefectNTC_T8",
    "SensorDefectNTC1",
    "reserved_47",
    "DutyCycleTooHigh",
    "Control_DCDC_Fault",
    "HardFault",
    "FieldtestActive",
    "SimulationActive",
    "EventMemoryIncompatible",
    "SettingsIncompatible",
    "PS_SetFault_Error",
    "HWprotect_Error_3V3",
    "HWprotect_OV_HV_MICRO2",
    "HWprotect_ERROR_FAN",
    "HWprotect_ENABLE_UREG_MC",
    "PS_SetFault_P_HV_Soll_tooPos",
    "PS_SetFault_P_HV_Soll_tooNeg",
    "PS_SetFault_V_HV_Top_Soll_tooHigh",
    "PS_SetFault_V_HV_Top_Soll_tooLow",
    "PS_SetFault_V_HV_Bottom_Soll_tooHigh",
    "PS_SetFault_V_HV_Bottom_Soll_tooLow",
    "PS_SetFault_V_LV_Top_Soll_tooHigh",
    "PS_SetFault_V_LV_Top_Soll_tooLow",
    "PS_SetFault_V_LV_Bottom_Soll_tooHigh",
    "PS_SetFault_V_LV_Bottom_Soll_tooLow",
    "PS_SetFault_I_LV_Pos_Soll_tooPos",
    "PS_SetFault_I_LV_Pos_Soll_tooNeg",
    "PS_SetFault_I_LV_Neg_Soll_tooPos",
    "PS_SetFault_I_LV_Neg_Soll_tooNeg",
    "V_HV_Measurement_Warning",
    "12V_Supply_Startup_Error",
    "PowerLimitedVHVDerating",
    "BatteryWrongPolarity",
    "BlackStartupInProgress",
    "HMI_CommunicationTimeout_Elapsed",
    "reserved_80",
    "reserved_81",
    "reserved_82",
    "reserved_83",
    "reserved_84",
    "reserved_85",
    "reserved_86",
    "I_bat_discharge_max_too_low_for_Startup",
    "Standby_0W",
    "EndtestActive",
    "_obsolete_EVENT_ID_BNVS_RecordNotRestorable",
    "_obsolete_EVENT_ID_BNVS_RecordRestored",
    "WatchdogReset",
    "Branding_fault",
    "reserved_94",
    "reserved_95"
];

var relaysState = [
    "AllOpen",
    "DC1_Relay_Closed",
    "DC2_Relay_Closed",
    "AC_Relay1_Closed",
    "AC_Relay2_Closed",
    "OpenCollectorOutput1_Active",
    "OpenCollectorOutput2_Active",
    "OpenCollectorOutput3_Active"
];

var startupState = {
    0x0000 : "StabilizeMcuSupply"              ,
    0x0010 : "StartHighSidePwm"                ,
    0x0020 : "StartAuxSupply"                  ,
    0x0030 : "StartMonitoring"                 ,
    0x0040 : "ThermalManagement"               ,
    0x0050 : "StartProtection"                 ,
    0x0058 : "CheckIslanding"                  ,
    0x0060 : "DegaussRCD"                      ,
    0x0070 : "GetAcOffset"                     ,
    0x0080 : "SwitchOnRelaisSupply"            ,
    0x0088 : "CheckStrings"                    ,
    0x008C : "EstablishLink"                   ,
    0x008D : "BlackStart"                      ,
    0x0090 : "TestAcRelais"                    ,
    0x00A0 : "TestDcRelais"                    ,
    0x00B0 : "SwitchOnDcRelais"                ,
    0x00B8 : "CheckDcShortcircuitAndPolarity"  ,
    0x00C0 : "GetDcOffset"                     ,
    0x00D0 : "TestRcd"                         ,
    0x00E0 : "IsolationCheck"                  ,
    0x00E4 : "SwitchOnENS"                     ,
    0x00E8 : "ReestablishLink"                 ,
    0x00EC : "RecheckIslanding"                ,
    0x00ED : "EstablishIslandingLink"          ,
    0x00EE : "ConfirmIslanding"                ,
    0x00F0 : "WaitEnsClearance"                ,
    0x0100 : "EstablishAcVoltage"              ,
    0x0108 : "RunIslanding"                    ,
    0x0110 : "RunGrid"                         ,
    0x0118 : "CheckShortFault"                 ,
    0x0120 : "SafeState"                       ,
    0x0130 : "Sleep"                           ,
    0x0138 : "SleepAfterIslanding"             ,
    0x0140 : "ShutdownForSleep"                ,
    0x0150 : "SystemReset"                     ,
    0x0160 : "WaitForReset"                    
};