/** Prevent JSHint warning about functions called from HTML sites. */
/* exported casc_enum, lng, tooltip system_state_name, tooltip, system_state_name,
system_type_name, batt_type_name, pwr_unit_type_name, pwr_unit_status_enum, enfluri_name,
OnOff_lang, NoneAvailable_lang, feature_state, condition_state, battery_state,
BatteryPhase, TimeZoneArray, CEI_Status, SysUpdateState, bms_status_enum,
CountryCodeArray, Country_enum, BMZ_WizardState, wallbox_adress_name, wallbox_unknown_hw_type,
wallbox_state_name, inverterNames, Samsung_Wizard */

var lng = {
	"TODAY": "TODAY",
	"YESTERDAY": "YESTERDAY",
	"WEEK": "WEEK",
	"MONTH": "MONTH",
	"YEAR": "YEAR",
	"OVERALL": "TOTAL",
	"LAST24": "LAST 24H",
	"Status_houseConsumption": "HOUSE CONSUMPTION",
	"Status_batteryCharge": "BATTERY CHARGE",
	"Status_gridImport": "GRID IMPORT",
	"Status_pvGenerated": "PV-GENERATION",
	"Status_batteryDischarge": "BATTERY DISCHARGE",
	"Status_gridExport": "GRID EXPORT",
	"Status_PU0": "1. HEATER CONSUMPTION",
	"Status_PU1": "2. HEATER CONSUMPTION",
	"Status_PU2": "3. HEATER CONSUMPTION",
	"Status_PU3": "4. HEATER CONSUMPTION",
	"Status_PU4": "5. HEATER CONSUMPTION",
	"Status_PU5": "6. HEATER CONSUMPTION",
	"USERNAME": "USERNAME",
	"PASSWORD": "PASSWORD",
	"Logout": "Logout",
	"Save": "Save",
	"Delete": "Delete",
	"Close": "Close",
	"Next": "Next",
	"Previous": "Back",
	"Check": "Check",
	"SPSSTOP": "STOP",
	"ERROR": "ERROR",
	"CHECK_INTERNET_RESULT_OK": "OK",
	"CHECK_INTERNET_RESULT_CHECK": "Checking...",
	"CHECK_INTERNET_RESULT_NONE": "Error!",
	"ALERT_ERROR": "Error! ",
	"WIZARD_ERROR_EULA": "Your need to accept the terms of license!",
	"WIZARD_CHECK_FIELDS_ERROR": "Please check the red marked fields!",
	"WIZARD_CHECK_LOGIN_ERROR": "Wrong e-mail address or password. Please check.",
	"WIZARD_CHECK_LOGIN_BUTTON": "Please log in to your installer account.",
	"WIZARD_CHECK_LOGIN_SUCCESS": "Logged in successfully. ",
	"WIZARD_CHECK_LOGIN_CONTRACTOR": "Please select contracting party if applicable.",
	"WIZARD_CHECK_PASSWORD_FIELD_ERROR_SHORT": "Min. password length is 8 characters!",
	"WIZARD_CHECK_PASSWORD_FIELD_ERROR_NO_MATCH": "Password-fields are not equal!",
	"WIZARD_CHECK_EMAIL_FIELD_ERROR_NO_MATCH": "Email-fields are not equal!",
	"WIZARD_CHECK_EMAIL_FIELD_ERROR_VALIDATION": "Please enter a valid email format e.g.: maxmustermann@muster.de !",
	"WIZARD_CHECK_EMAIL_FIELD_ERROR_SAME_INSTALLER_CUSTOMER": "Email addresses of installer and owner must not be the same!",
	"WIZARD_CHECK_SENEC_SERIAL_FIELD_ERROR_VALIDATION": "The SENEC serial number does not correspond to a valid format.",
	"WIZARD_CHECK_CONFIRMATION_ERROR_CHECK_ALL": "You need to confirm all points and correct all marked fields!",
	"WIZARD_CHECK_BATTERY_PHASE_ERROR": "The phase of your SENEC system has to be identical with at least one phase of your PV inverter\nor at least one PV inverter has to be triphase!\nPlease correct this on the extended settings tab.",
	"WIZARD_CHECK_BATTERY_NEED_PHASE": "You have to select a battery phase!",
	"WIZARD_INVERTERS_METER_HOUSE_CHECK": "If you do not activate power meter 2 or 3, you have to activate at least one certified PV inverter!",
	"WIZARD_NOTIFY_NO_INTERNET_REGACTUALER": "Important: You do not have an internet connection and you need to register your SENEC later on!\nThe installation is completed, you can close the assistant window now.",
	"WIZARD_NOTIFY_NO_CONN_TO_MCU": "ATTENTION: There is no connection to your SENEC-System.\nTherefore the configuration process can not be completed!\nPlease check the ethernet connection to your SENEC!",
	"WIZARD_CHECK_PV_MAX_POWER": "PV-Power has to be bigger than zero!",
	"WIZARD_CHECK_IP_ADDRESS": "Please enter a correct IP-Address!",
	"WIZARD_CHECK_PU_MAX_POWER": "Please enter a positive power value of max 2000W per phase!",
	"WIZARD_CHECK_PU_TOTAL_POWER": "Please enter any power values!",
	"WIZARD_CHECK_PU_MIN_TEMP": "Min temperature must be bigger than max temperature!",
	"WIZARD_CHECK_PU_TEMP_RANGE": "A given temperature value is out of range.",
	"WIZARD_CHECK_GRID_CONNECTION": "Please select type of mains connection!",
	"WIZARD_CHECK_ENFLURI": "Please select one checkbox for the power meter configuration!",
	"WIZARD_CHECK_TIMEZONE": "A time zone must be selected.",
	"WIZARD_CHECK_POS_DECIMAL": "Only a positive number can be specified.",
	"WIZARD_CHECK_RS485": "Addresses must not be the same.",
	"WIZARD_CHECK_SERIAL": "Invalid serial number.",
	"WIZARD_CHECK_PERCENTAGE": "Values must be 0-100%.",
	"WIZARD_CHECK_PV_POWER": "The peak power must be at least 100W.",
	"WIZARD_EG_ERROR_NEED_INITIAL_CONFIG": "First you have to configure your SENEC-System with the 'Configuration-Wizard', afterwards you can run the Econamic Grid registration!",
	"WIZARD_GRID_ERROR_NEED_INITIAL_CONFIG": "You must first configure the SENEC system with the 'Configuration Wizard' before you can set the grid parameters!",
	"WIZARD_EG_CHECK_FIELDS_ERROR": "Please check the red marked fields!",
	"WIZARD_EG_ERROR_EULA": "Error ! General terms and conditions, and the cancellation policy has to be accepted. \nFurthermore please select your types of control energy!",
	"WIZARD_EG_CHECK_EMAIL_FIELD_ERROR_NO_MATCH": "Email-fields are not equal!",
	"WIZARD_EG_CHECK_EMAIL_FIELD_ERROR_VALIDATION": "lease enter a valid email format e.g.: maxmustermann@muster.de !",
	"WIZARD_EG_CHECK_DEBIT_AUTHORITY_ERROR": "Please accept the direct debit authority!",
	"WIZARD_EG_CHECK_CONFIRMATION_ERROR_CHECK_ALL": "You need to confirm all points and correct all marked fields!",
	"WIZARD_EG_ERROR_NO_POWERMETER_SERIAL": "Meter ID not received!",
	"WIZARD_EG_TEST_INSTALLATION_PENDING": "Test is running ...",
	"WIZARD_EG_TEST_INSTALLATION_RESULT_ERROR": "ERROR!",
	"WIZARD_EG_TEST_INSTALLATION_POWERMETER_COM_OK": "OK!",
	"WIZARD_EG_TEST_INSTALLATION_POWERMETER_READ_OK": "OK!",
	"WIZARD_EG_TEST_INSTALLATION_SWITCH_COM_OK": "OK!",
	"WIZARD_EG_TEST_INSTALLATION_NO_RESULTS": "Some tests did not run probably!\n\n Please check the wired connection and your electrical installation!\n Afterwards rerun the test through clicking on 'Start test!' !",
	"WIZARD_EG_TEST_INSTALLATION_ERRORS": "Errors occurred during testing the Econamic Grid functionality!\n\n Please check your Econamic-Grid installation and wiring!\n Afterwards rerun the test through clicking on 'Start test!' !",
	"WIZARD_EG_NO_INTERNET": "ATTENTION: There is no internet connection. Please provide a stable internet connection!",
	"WIZARD_EG_SUBMIT_NO_INTERNET": "ATTENTION: The internet connection has gone away! Please provide a stable internet connection! Afterwards start the Econamid-Grid assistant again and rerun the registration!",
	"YES": "Yes",
	"NO": "No",
	"NOT_POSSIBLE": "not possible",
	/*User Definitions*/
	"OWNER": "Owner",
	"INSTALLER": "Installer",
	"MANUFACTURER": "Manufacturer",
	"SUPERUSER": "Superuser",
	"TESTER": "Tester",
	"UNKNOWN": "Unknown",
	/*stat0 Page*/
	"HOMECONSUMPTION": "HOMECONSUMPTION",
	"BATTERYCHARGE": "BATTERY-CHARGE",
	"GRIDIMPORT": "GRID-IMPORT",
	"PVGENERATED": "GENERATED PV-POWER",
	"BATTERYDISCHARGE": "BATTERY-DISCHARGE",
	"GRIDEXPORT": "GRID-EXPORT",
	/*index.html*/
	"lStatus": "STATUS",
	"lKonfiguration": "SETTINGS",
	"lSetup": "SETUP",
	/*Headings*/
	"lDateTime": "DATE/TIME",
	"lPowerSockets": "POWER SOCKETS",
	"lInformation": "INFORMATION",
	"lBatteryMaintenance": "MAINTENANCE",
	"lStartTest": "START & TEST",
	"lHeatingRod": "POWER UNIT",
	"lAccumulatorHeader": "BATTERY",
	"lAutarkyHeader": "AUTARKY",
	"lPeakShaving": "PEAK-SHAVING",
	"lSelftest" : "SELFTEST",
	/*konfInf.html*/
	"lOperatingHours": "OPERATING HOURS (h):",
	"lLastMaintenance": "LAST MAINTENANCE (d):",
	"lType": "TYPE :",
	"lState": "STATE:",
	"lNextState": "DELAYED STATE:",
	"lMCUID": "CONTROLER-SN:",
	"lMACADDRESS": "MAC-ADRESS:",
	"lSystem": "SYSTEM:",
	"lFrequency": "FREQUENCY (Hz):",
	"lVoltage": "VOLTAGE (V):",
	"lCurrent": "CURRENT (A):",
	"lPower": "POWER (W):",
	"lTotalPower": "TOTAL POWER (W):",
	"lAccu": "BATTERY:",
	"lPowerValues": "POWER VALUE:",
	"lBatteryPower": "BATTERY POWER (W):",
	"lBatteryVoltage": "BATTERY VOLTAGE (V):",
	"lBatteryCurrent": "BATTERY CURRENT (A):",
	"lBatteryCurrentEach": "CURRENT (A) PER INVERTER:",
	"lMaxCapacity": "MAXIMUM CAPACITY (Ah):",
	"lFuelGauge": "FUELGAUGE (%):",
    "lAcApparentPower": "APPARENT POWER (VA):",
    "lAcActivePower": "ACTIVE POWER (W):",
    "lAcReactivePower": "REACTIVE POWER (VAr):",
	"lTotalCharge": "TOTAL CHARGED ENERGY (kWh):",
	"lNoDesulfatCharge": "DESULFATATIONCHARGES:",
	"lBattInverterType": "INVERTER-TYPE :",
	"lInv1Temp": "INVERTER 1 TEMP. (°C):",
	"lInv2Temp": "INVERTER 2 TEMP. (°C):",
	"lInv3Temp": "INVERTER 3 TEMP. (°C):",
	"lNoLiModule": "LI-MODULE COUNT :",
	"lInverterPhase": "CHARGEPHASE:",
	"lTimeRemainEqual": "REM. EQUALIZATION (min):",
	"lTimeRemainCharge": "REM. CHARGE (min):",
	"lDurationCharge": "TOTAL CHARGE DURATION (min):",
	"lHomeconsumption": "HOUSECONSUMPTION (W):",
	"lPVGeneration": "PV-GENERATION (W):",
	"lPVLimit": "PV-LIMITATION (%):",
	"lMpp0Generation":"GENERATION MPP 1",
	"lMpp1Generation":"GENERATION MPP 2",
	"lMpp2Generation":"GENERATION MPP 3",
	"lUnbalancedLoadLimit": "POWERSKEW:",
	"lExportLimit": "EXPORT-LIMIT.:",
	"lVoltageLimit": "LOW VOLTAGE-LIMIT.:",
	"lCapacityTestValue": "CAPACITY TEST RES. (Wh):",
	"lIslandMode": "BACKUP POWER MODE:",
	"lPUConTotal": "PU-CONSUMPTION (W):",
	"lFeaturePackage": "FEATURE PACKAGES:",
	"lFeatureIsland": "BACKUP POWER MODE:",
	"lFeatureIslandPro": "BACKUP POWER MODE PRO:",
	"lFeatureSockets": "POWER-SOCKETS:",
	"lFeatureHeatBox": "HEATING-ELEMENT:",
	"lFeaturePeakShaving": "PEAK-SHAVING:",
	"lFeatureEcoGrid": "ECONAMIC-GRID:",
	"lFeatureCloud": "SENEC.CLOUD:",
	"lFeatureCar": "CHARGE-STATION:",
	"lCEIStatus": "STATUS GRID PARAMETER CONTROL (CEI)",
	"lFeatureSHKW": "SOLARINVERT SHKW:",
	"lFeatureSGready": "SG-READY:",
	/*accu0.html*/
	"lCapacity": "CAPACITY (%):",
	/*AccuTest.html*/
	"lAccuStartTest": "BATTERY-START&TEST",
	"lStopInitialCharge": "INITIAL CHARGE<br>STOP",
	"lStartInitialCharge": "INITIAL CHARGE<br>START",
	"lInitialChargeNotStarted": "Initial charge not started...",
	"lInitialChargeFinished": "Initial charge finished...",
	"lInitialChargeAborted": "Initial charge aborted...",
	"lInitialChargeStarted": "Initial charge started...",
	"lInitialCharge10minCharge": "Voltage reversal test (10 min Charge)",
	"lInitialCharge10minChargeLI": "10 min Charge",
	"lInitialCharge5minDischarge": "Voltage reversal test (5 min Discharge)",
	"lInitialCharge5minDischargeLI": "5 min Discharge",
	"lInitialChargeHint1_0": "Voltage differnece (Charge and discharge) (V): ",
	"lInitialChargeHint1_1": "<br>Max. chargecurrent (A): ",
	"lInitialChargeHint1_2": "<br>Max. dischargecurrent (A): ",
	"lInitialChargeHint1_3": "<br>Hint: During the next 5min of discharge: Please check if <br>the battery inverter fans are switched on!",
	"lInitialChargeHint1_4": "<br><button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Please confirm</p></button>\n\<button id=InitChargeAckbtn onclick='InitChargeRerun();'><p>Rerun</p></button>\n",
	"lInitialCharge5minTest": "Pole connector test (5min discharge)",
	"lInitialChargeQuestionSenecBatt": "<p>Please check the pole connector on heat.</p><br>\n<p>Were the battery inverter fans active?</p><br>\n<button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Please confirm</p></button>\n\<button id=InitChargeAckbtn onclick='InitChargeRerun();'><p>Rerun</p></button>",
	"lInitialChargeQuestionOther": "<p>Please check the pole connector on heat.</p><br>\n<button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Please confirm</p></button>\n\<button id=InitChargeAckbtn onclick='InitChargeRerun();'><p>Rerun</p></button>",
	"lInitialChargeFullCharge": "Final full charge...",
	"lInitialChargeDone": "Finished",
	"lInitialChargeFinalHintPB": "<p>Initial charge finished. Backup power mode can be unlocked.</p><br>\n<button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Please confirm</p></button>",
	"lInitialChargeFinalHintLI": "<p>Initial charge finished. Backup power mode can be unlocked.</p><br>\n<p>Please make sure that the battery cells are refilled with destilled water.</p><br>\n<button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Please confirm</p></button>",
	"lInitialChargeUnknownState": "unknown state",
	"lInitialChargeStep1": "CHARGE 10 min",
	"lInitialChargeStep2": "DISCHARGE 5 min",
	"lInitialChargeStep3": "RESULT",
	"lInitialChargeStep4": "DISCHARGE 5 min",
	"lInitialChargeStep5": "RESULT",
	"lInitialChargeStep6": "FULL CHARGE",
	"lInitialChargeProtokoll": "TEST PROTOCOL:",
	"lInitialChargeState": "Initial charge state:",
	"lInitialChargeMinVoltage": "Min. Voltage (V):",
	"lInitialChargeMaxVoltage": "Max. Voltage (V):",
	"lInitialChargeVoltageDiff": "Voltage difference (V):",
	"lInitialChargeMaxChargeCurrent": "Max. charging current (A):",
	"lInitialChargeMaxDischargeCurrent": "Max. discharging current (A):",
	"lInitialChargeCurrent": "Actual current (A):",
	"lInitialChargeVoltage": "Actual voltage (V):",
	"lInitialChargeWaterRefill": "Ready for water refill?",
	"lInitialChargeFuelGauge": "Battery level (%):",
	"lInitialChargeStartCriteria": "Battery level must be less than 90%.",
	/*ksockets.html*/
	"lSocketsPowerStateOn": "ON",
	"lSocketsPowerStateOff": "OFF",
	"lSocketsLabel": "Sockets",
	"lSocketsSocketTop": "Socket:",
	"lSocketsPermanentOn": "Permanent On:",
	"lSocketsActivateAuto": "Activate Automatic:",
	"lSocketsPowerOn": "Turn-on Threshold (W):",
	"lSocketsPowerOff": "Turn-off Threshold (W):",
	"lSocketsExcessDuration": "Duration Of Power Excess (min):",
	"lSocketsDuration": "Duration Of Socket Switched On (min):",
	"lSocketsPeriodDuration": "Switchingperiod (min):",
	"lSocketsSocketBottom": "SOCKET:",
	"lSocketsRemainTime": "Remaining Time(min):",
	"lSocketsState": "State:",
	"lSocketsSave": "Save",
	"lSocketsActivateTime" : "Activate Switching Time",
	"lSocketsTime" : "Switching Time (HH:MM)",
	"lSocketsAlreadySwitched": "Already switched:",

	/*login.html*/
	"lLoginLabel": "LOGIN",
	"lLoginHint": "FOR THIS AREA YOU NEED A VALID LOGIN!",
	"lLoginUser": "USER:",
	"lLoginPassword": "PASSWORD:",
	"lLoginSignIn": "LOGIN",
	/*power_unit_info.html*/
	"lPWRUTitle0": "Power Unit:",
	"lPWRUState0": "STATE:",
	"lPWRUPowerEach0": "POWER PER PHASE (W):",
	"lPWRUPowerTotal0": "TOTAL POWER (W):",
	"lPWRUTempMin0": "MIN TEMPERATURE:",
	"lPWRUTempMax0": "MAX TEMPERATURE:",
	"lPWRUTempMin_Now0": "ACTUAL TEMPERATURE MIN:",
	"lPWRUTempMax_Now0": "ACTUAL TEMPERATURE MAX:",
	"lPWRURev0": "REVISION:",
	"lPWRUTitle1": "Power Unit:",
	"lPWRUState1": "STATE:",
	"lPWRUPowerEach1": "POWER PER PHASE (W):",
	"lPWRUPowerTotal1": "TOTAL POWER (W):",
	"lPWRUTempMin1": "MIN TEMPERATURE:",
	"lPWRUTempMax1": "MAX TEMPERATURE:",
	"lPWRUTempMin_Now1": "ACTUAL TEMPERATURE MIN:",
	"lPWRUTempMax_Now1": "ACTUAL TEMPERATURE MAX:",
	"lPWRURev1": "REVISION:",
	"lPWRUTitle2": "Power Unit:",
	"lPWRUState2": "STATE:",
	"lPWRUPowerEach2": "POWER PER PHASE (W):",
	"lPWRUPowerTotal2": "TOTAL POWER (W):",
	"lPWRUTempMin2": "MIN TEMPERATURE:",
	"lPWRUTempMax2": "MAX TEMPERATURE:",
	"lPWRUTempMin_Now2": "ACTUAL TEMPERATURE MIN:",
	"lPWRUTempMax_Now2": "ACTUAL TEMPERATURE MAX:",
	"lPWRURev2": "REVISION:",
	"lPWRUTitle3": "Power Unit:",
	"lPWRUState3": "STATE:",
	"lPWRUPowerEach3": "POWER PER PHASE (W):",
	"lPWRUPowerTotal3": "TOTAL POWER (W):",
	"lPWRUTempMin3": "MIN TEMPERATURE:",
	"lPWRUTempMax3": "MAX TEMPERATURE:",
	"lPWRUTempMin_Now3": "ACTUAL TEMPERATURE MIN:",
	"lPWRUTempMax_Now3": "ACTUAL TEMPERATURE MAX:",
	"lPWRURev3": "REVISION:",
	"lPWRUTitle4": "Power Unit:",
	"lPWRUState4": "STATE:",
	"lPWRUPowerEach4": "POWER PER PHASE (W):",
	"lPWRUPowerTotal4": "TOTAL POWER (W):",
	"lPWRUTempMin4": "MIN TEMPERATURE:",
	"lPWRUTempMax4": "MAX TEMPERATURE:",
	"lPWRUTempMin_Now4": "ACTUAL TEMPERATURE MIN:",
	"lPWRUTempMax_Now4": "ACTUAL TEMPERATURE MAX:",
	"lPWRURev4": "REVISION:",
	"lPWRUTitle5": "Power Unit:",
	"lPWRUState5": "STATE:",
	"lPWRUPowerEach5": "POWER PER PHASE (W):",
	"lPWRUPowerTotal5": "TOTAL POWER (W):",
	"lPWRUTempMin5": "MIN TEMPERATURE:",
	"lPWRUTempMax5": "MAX TEMPERATURE:",
	"lPWRUTempMin_Now5": "ACTUAL TEMPERATURE MIN:",
	"lPWRUTempMax_Now5": "ACTUAL TEMPERATURE MAX:",
	"lPWRURev5": "REVISION:",
	"lPWRUNoConfig": "No power unit configured!",
	/*wallbox_info.html*/
	"lWallboxTitle0": "Wallbox 1:",
	"lWallboxTitle1": "Wallbox 2:",
	"lWallboxTitle2": "Wallbox 3:",
	"lWallboxTitle3": "Wallbox 4:",
	"lWallboxMaxCurrent0": "MAX. CHARGING CURRENT (A):",
	"lWallboxMaxCurrent1": "MAX. CHARGING CURRENT (A):",
	"lWallboxMaxCurrent2": "MAX. CHARGING CURRENT (A):",
	"lWallboxMaxCurrent3": "MAX. CHARGING CURRENT (A):",
	"lWallboxState0": "STATE:",
	"lWallboxState1": "STATE:",
	"lWallboxState2": "STATE:",
	"lWallboxState3": "STATE:",
	"lWallboxTotalPower0": "TOTAL POWER (VA):",
	"lWallboxTotalPower1": "TOTAL POWER (VA):",
	"lWallboxTotalPower2": "TOTAL POWER (VA):",
	"lWallboxTotalPower3": "TOTAL POWER (VA):",
	"lWallboxRevision0": "REVISION:",
	"lWallboxRevision1": "REVISION:",
	"lWallboxRevision2": "REVISION:",
	"lWallboxRevision3": "REVISION:",
	"lWallboxHardware0": "HARDWARE (pcba-Type):",
	"lWallboxHardware1": "HARDWARE (pcba-Type):",
	"lWallboxHardware2": "HARDWARE (pcba-Type):",
	"lWallboxHardware3": "HARDWARE (pcba-Type):",
	"lWallboxCurrent0": "CURRENT PER PHASE (A):",
	"lWallboxCurrent1": "CURRENT PER PHASE (A):",
	"lWallboxCurrent2": "CURRENT PER PHASE (A):",
	"lWallboxCurrent3": "CURRENT PER PHASE (A):",
	"lWallboxNoConfig": "No Wallbox configured!",
	/*ksetup1.html*/
	"lSetupBatteryVoltage": "Battery voltage (V)",
	"lSetupBatteryCurrent": "Battery curremt (A)",
	"lSetupNumDesulfatCharges": "Desulfatationcharges",
	"lSetupBatteryTemp": "Battery temperature (°C)",
	"lSetupCaseTemp": "Case temperature (°C)",
	"lSetupServerConnectionState": "Server connection",
	"lSetupBatteryInverterConnectionState": "Battery inverter",
	"lSetupPowerMeter1ConnectionState": "Power meter 1",
	"lSetupPowerMeter2ConnectionState": "Power meter 2",
	"lSetupPVConnectionState": "PV inverter",
	"lSetupPWRUnitConnectionState": "Power Unit",
	"lSetupMasterConnectionState": "Connection to Master",
	"lSetupNumConnectedSlaves": "Connected Slaves:",
	"lSetupEGSwitchConnectionState": "EG-Switch Box",
	"lSetupIskraConnectionState": "Iskra Meter",
	"lSetupPS1": "Socket 1",
	"lSetupPS2": "Socket 2",
	"lSetupPump": "Pump",
	"lSetupXCOM": "Xcom",
	"lSetupFAN": "Fans",
	"lSetupAutoCycle": "Auto Cycle",
	"lSetupSetTime": "Set time",
	"lSetupReset": "Reset:",
	"lSetupResetStatistics": "Total statistics",
	"lSetupSetBatteryProtection": "Battery protection mode",
	"lSetupPauseSpecial": "Pause Specialcharge",
	"lSetupUseInternet": "Internet usage",
	"lSetupFWUpdate": "Software-Update",
	"lSetupNAUpdate": "NSP update from SD card",
	"lSetupOverwriteFeatures": "Unlock additional features",
	"lSetupConfigWizard": "Configuration wizard ",
	"lSetupEGWizard": "Econamic-Grid wizard",
	"lSetupRestartMCU": "Restart system",
	"lSetupCapacityTest": "Capacity test",
	"lSetupTestPower": "Test power (W)",
	"lSetupCharge": "Charge",
	"lSetupdDischarge": "Discharge",
	"lSetupTestPowerError": "Test power must not be empty!",
	"lSetupUpdateAvailable": "Update available.",
	"lSetupNoUpdateAvailable": "No update available at the moment.",
	"lSetupLanguageSelection": "Language selection",
	"lSetupFullWizard": "Expand assistent",
	"lSetupInverterUpdate": "Inverter update from SD card",
	"lSetupPvWizard" : "PV wizard",
	/*Wizard file*/
	"wizard-file": './wizard_EN.html',
	/*modal.js*/
	"lNoValidIP": ' is no valid IP-Address.',
	"lErrMaxConnPwr": 'max. power line load can not be zero.',
	"lErrMaxInvPwr": 'The max. inverter power must not be smaller than 1W!',
	"lErrModbusAddr": 'Modbus-addresses must be between 1 and 254!',
	"lWIZARD_ADDR_SLAVE": "Slave Address:",
	"lWIZARD_ADDR_1": "Address 1:",
	"lConfirmAccuPole": "The terminal connectors connect the battery module to the connection rail with a starting torque of 5 Nm.",
	/*Konfiguration.AccuService.html*/
	"lAccuServiceWaterRefill": "Maintenance charge ready, please refill the battery cells with water and confirm.",
	"lAccuServiceMntRunning": "Maintenance charge running ...",
	"lAccuServiceMntNeeded": "Maintenance needed, please perform maintenance charge.",
	"lAccuServiceFilterNeeded": "Filterchange needed!",
	"lAccuServiceFullcharge": "Full charge",
	"lAccuServiceReleaseDischarge": "Release discharge",
	"lAccuServiceDesulfatationCharge": "Desulfatationcharge",
	"lAccuServiceEqualizationCarge": "Equalizationcharge",
	"lAccuServiceMntCharge": "Maintenance charge",
	"lAccuServicePrepareModule": "Prepare module replacement",
	"lAccuServiceConfirmFilter": "Confirm filterchange",
	/*kpeakshaving.html*/
	"lPSerrorPercentage": "Reserved capacity must be between 0 and 100%!",
	"lPSerrorTime": "Please checked entered time!",
	"lPSActivate": "Activate Peak-Shaving",
	"lPSReservoirMsg1": "When",
	"lPSReservoirMsg2": "% battery charge is reached, the energy generated thereafter is fed into the grid. The battery will be charged again, if more energy is generated than can be fed in (feed-in limiter) or the set time has been reached.",
	"lPSUntilTime": "UNTIL TIME:",
	"lPSHeader": "CONFIGURATION PEAK-SHAVING",
	"lPSSettings": "SETTINGS:",
	/*Page Loading*/
	"lLoadPage": "Loading...",
	/*Package Checker*/
	"true": "Valid",
	"false": "Invalid",
	"confirmed": "Redeemed",
	"AKTIVIERUNGSCODE_UNBEKANNT": "This code is unknown!",
	"AKTIVIERUNGSCODE_VON_ANDERER_STEUEREINHEIT_VERWENDET": "This code is already activated by another unit!",
	"STEUEREINHEIT_BEREITS_MIT_ANDEREM_AKTIVIERUNGSCODE_REGISTRIERT": "This system is already activated for this package!",
	"lNotActive": "This feature is not activated!",
	/*modal.update.html*/
	"lUpdateFWUpdate": "Software-Update available!",
	"lUpdateRequest": "Do you want to update your system?",
	"lUpdateLater": "Later",
	"lUpdateNow": "Update Now",
	"lUpdateStatus": "Update Status:",
	/*09-06-2017
	power_unit_info.html*/
	"lPUmin0": "Minimum [°C]:",
	"lPUmax0": "Maximum [°C]:",
	"lPUSave0": "Save",
	"lPUmin1": "Minimum [°C]:",
	"lPUmax1": "Maximum [°C]:",
	"lPUSave1": "Save",
	"lPUmin2": "Minimum [°C]:",
	"lPUmax2": "Maximum [°C]:",
	"lPUSave2": "Save",
	"lPUmin3": "Minimum [°C]:",
	"lPUmax3": "Maximum [°C]:",
	"lPUSave3": "Save",
	"lPUmin4": "Minimum [°C]:",
	"lPUmax4": "Maximum [°C]:",
	"lPUSave4": "Save",
	"lPUmin5": "Minimum [°C]:",
	"lPUmax5": "Maximum [°C]:",
	"lPUSave5": "Save",
	/*12-06-2017
	wizard*/
	"lWizardPVOnly": "PV-Generation",
	"lWizardMinTempOnly": "Only temperature control",
	"lWizardPUConnectionError": "Caution: The operating mode setting for the power control units has been set to 'Only PV-Generation'!",
	/*19-06-2017
	cei-wizard*/
	"lCEIHeader": "CEI-Wizard",
	"lCEIsyncFreqMax": "Rest frequency - upper limit [mHz]",
	"lCEIsyncFreqMin": "Rest frequency - lower limit [mHz]",
	"lCEIreconnectTime": "Connection delay [s]",
	"lCEIreductionDrop": "Power reduction ratio [1/s]",
	"lCEIcosPhiLockIn": "Active power lock-in [%]",
	"lCEIcosPhiLockOut": "Active power lock-out [%]",
	"lCEIstabUpperThresh": "Active power limitation - upper limit [mHz]",
	"lCEIstabLowerThresh": "Active power limitation - lower limit [mHz]",
	"lCEIstabUpperCorner": "Active power limitation - upper cut-off frequency [mHz]",
	"lCEIstabLowerCorner": "Active power limitation - lower cut-off frequency [mHz]",
	"lCEIactivationDelay": "Activation delay [ms]",
	"lCEIvoltageThresh": "Voltage threshold [%]",
	"lCEIcosPhiFix": "Locked power factor",
	"lCEIcosPhiLabel": "Power factor",
	/*07-07-2017
	wizard*/
	"lWizardChargePrio1": "Battery -> Power Unit -> Grid export",
	"lWizardChargePrio2": "Power Unit -> Battery -> Grid export",
	"lWizardChargePrio3": "Battery -> Grid export -> Power Unit",
	"lWizardChargePrio4": "Not needed.",
	/*Nulleinspeisung / Volleinspeisung*/
	"lWizardChargePrio1_NoExport": "Battery -> Power Unit",
	"lWizardChargePrio2_NoExport": "Power Unit -> Battery",
	"lSetupGridParameter": "Grid parameter",
    /* konfInf.html */
	"lRevMCU": "REVISION MCU:",
	"lRevMCUBL": "REVISION MCU-BL:",
	"lRevGUI": "REVISION GUI:",
	"lRevNPU": "REVISION NPU-REGS:",
	"lRevNPUImage": "REVISION NPU-IMAGE:",
	"lRevINV": "REVISION INV:",
	"lRevHMI": "REVISION HMI:",
	"lRevPU":  "REVISION PU:",
	"lRevBDC":  "REVISION BDC:",
	"lRevNSP": "REVISION NSP:",
	/* OffPeak */
	"lOffPeak_Duration": "OFFPEAK-REMAINING (min):",
    /* 30-08-2017
       wizard */
    "lErrAbsoluteFeedInPower": "The feed-in power can not be greater than the generation.",
    /* 24.10.2017 modal.js */
    "lErrChargePrioNotSelected": "Charge priority not selected!",
    /* 03.11.2017 konfInf.html */
    "lCountryVar": "COUNTRY VARIANT:",
    /* Alert messages for peakshaving/zero export */
    "lAlertZeroExportActive": "Attention: Peakshaving can not be used if no grid feed is allowed.",
    "lAlertZeroExportSockets": "Attention: Switching contacts can only be used with the switching period option or switched on permanent.",
    "lAlertZeroExportSet": "Attention: Enabling the zero export will disable peakshaving and allow only switching periods for the switching contacts.",
    "lAUVoltWattCharge": "Volt-Watt mode charge",
    "lAUVoltWattDischarge": "Volt-Watt mode discharge",
    "lAUVoltWattDischargeValues": "Parameter",
    "lAUVoltWattChargeValues": "Parameter",
    "lAUFreqIncMode": "Frequency increase mode",
    "lAUFreqDecMode": "Frequceny decrease mode",
    "lAUVoltVarMode": "Volt-Var mode",
    "lAUPowerRateLimits": "Power rate limits",
    "lAUSoftRampUp": "Soft ramp up",
    "lAURampChangesInEnergy": "Changes in energy source operation",
    "lAUGradientInc": "Gradient Wgra+",
    "lAUGradientDec": "Gradient Wgra-",
    "lAUTargetType": "Cosphi (P) mode",
    "lAuLocalGridCodes": "Local grid code",
    "lAUFixedFac": "Fixed power factor mode",
    "lAUHeader": "Grid parameter Australia",
    "lCosPhi1": "cosPhi at 0% power",
    "lCosPhi2a": "cosPhi at X% power",
    "lCosPhi2b": "X (%)",
    "lCosPhi3": "cosPhi at 100% power",
    "lCosPhiReg": "Activate reactive power control",
    "l4105Header": "Grid parameters Germany",
    "lBatteryWizard": "Battery wizard",
    "lBatteryHeader": "Battery module wizard",
    "lStart": "Start",
    "lAbort": "Chancel",
    "lBatteryFuelgauge": "Fuelgauge: ",
    "lBatterySerial": "Serial: ",
    "lWizardVoltage": "Voltage: ",
    "lWizardCurrent": "Current: ",
    "Confirm": "Confirm",
    "Restart": "Restart",
    "lBatteryVersion": "FW-Version: ",
    "lWizardPackageFirstRun": "Packet activation is only possible after reopening the configuration wizard, as the SENEC system must first be registered on our web portal.",
    "lIslandModePackage": "SOFTWARE PACKAGE:",
    "lIslandModeStatus": "SYSTEM PRECONDITION:",
    "lIslandModeBattery": "BATTERY:",
    "lEmergModeCapacity": "Capacity:",
    "BMZClose": "Finish",
    /* VDE-AR-N4105 2019 (only applies to Germany) */
    "l4105cosphiSetting": "Individuelle Blindleistungsbereitstellung (CosPhi)",
    "l4105cosphiSettingIndividual": "Blindleistungsbereitstellung (CosPhi)",
    "l4105cosphiTimeLimit": "Zeit bis zum Erreichen der Blindleistungsvorgabe (s)",
    "l4105FRT": "Rückkehr zur erforderlichen Blindleistung nach Fehlerende (s)",
    "l4105activePowerControlOverFrequency": "Wirkleistungsanpassung bei Überfrequenz (Hz)",
    "l4105activePowerControlUnderFrequency": "Wirkleistungsanpassung bei Unterfrequenz (Hz)",
    "l4105activePowerControlDroopOverFrequency": "Statik bei Überfrequenz (%)",
    "l4105activePowerControlDroopUnderFrequency": "Statik bei Unterfrequenz (%)",
    "lPvWizardHeader": "PV wizard",
    "lInsulationResistance": "Insulation resistance in Ohm/V",
    "lStartSelftest": "Start Selftest",
    "lPv0Label": "PV 1:",
    "lPv1Label": "PV 2:",
    "idShowButton": "show",
    "idHideButton": "hide",
    "lLicense": "THIRD PARTY LICENSES",
    "lTempSensorWarning": "The minimum temperature control only works with temperature sensors. If none are configured, the heater will not turn on.",
    "lWbProhibited": "Wallbox usage prohibited by web portal.",
    "lStartFanTest": "Start fan test",
    "lConfirmFanTest": "Confirm fan test",
    "lRotateTrigger": "Rotate Logfile",
    "lGetNspLog": "NSP Logfile"
};

var tooltip = {
    "checkboxWizardAUresponsemode_0": "Limit charging power depending on the mains voltage.",
    "checkboxWizardAUresponsemode_1": "Limiting discharge power depending on the mains voltage.",
    "checkboxWizardAUresponsemode_2": "Limit charging power at overfrequency of the grid.",
    "checkboxWizardAUresponsemode_3": "Limit discharge power at mains overfrequency.",
    "checkboxWizardAUresponsemode_4": "Regulate reactive power depending on the mains voltage.",
    "GUI_DATA_BATINV1_TEMP": "Halfbridge 1, halfbridge 2, inductor. If available: Transformator core, transformator insulation.",
    "GUI_DATA_BATINV2_TEMP": "Halfbridge 1, halfbridge 2, inductor. If available: Transformator core, transformator insulation.",
    "GUI_DATA_BATINV3_TEMP": "Halfbridge 1, halfbridge 2, inductor. If available: Transformator core, transformator insulation.",
    "WIZARDDEVICE_WALLBOX_SLAVE_ADRESS0": "Address range: 1 to 16",
    "WIZARDDEVICE_WALLBOX_SLAVE_ADRESS1": "Address range: 1 to 16",
    "WIZARDDEVICE_WALLBOX_SLAVE_ADRESS2": "Address range: 1 to 16",
    "WIZARDDEVICE_WALLBOX_SLAVE_ADRESS3": "Address range: 1 to 16",
};

var system_state_name = {
    0: "INITIALSTATE",
    1: "ERROR INVERTER COMMUNICATION",
    2: "ERROR ELECTRICY METER",
    3: "RIPPLE CONTROL RECEIVER",
    4: "INITIAL CHARGE",
    5: "MAINTENANCE CHARGE",
    6: "MAINTENANCE READY",
    7: "MAINTENANCE REQUIRED",
    8: "MAN. SAFETY CHARGE",
    9: "SAFETY CHARGE READY",
    10:"FULL CHARGE",
    11:"EQUALIZATION: CHARGE",
    12:"DESULFATATION: CHARGE",
    13:"BATTERY FULL",
    14:"CHARGE",
    15:"BATTERY EMPTY",
    16:"DISCHARGE",
    17:"PV + DISCHARGE",
    18:"GRID + DISCHARGE",
    19:"PASSIVE",
    20:"OFF",
    21:"OWN CONSUMPTION",
    22:"RESTART",
    23:"MAN. EQUALIZATION: CHARGE",
    24:"MAN. DESULFATATION: CHARGE",
    25:"SAFETY CHARGE",
    26:"BATTERY PROTECTION MODE",
    27:"EG ERROR",
    28:"EG CHARGE",
    29:"EG DISCHARGE",
    30:"EG PASSIVE",
    31:"EG PROHIBIT CHARGE",
    32:"EG PROHIBIT DISCHARGE",
    33:"EMERGANCY CHARGE",
    34:"SOFTWARE UPDATE",
    35:"NSP ERROR",
    36:"NSP ERROR: GRID",
    37:"NSP ERROR: HARDWRE",
    38:"NO SERVER CONNECTION",
    39:"BMS ERROR",
    40:"MAINTENANCE: FILTER",
    41:"SLEEPING MODE",
    42:"WAITING EXCESS",
    43:"CAPACITY TEST: CHARGE",
    44:"CAPACITY TEST: DISCHARGE",
    45:"MAN. DESULFATATION: WAIT",
    46:"MAN. DESULFATATION: READY",
    47:"MAN. DESULFATATION: ERROR",
    48:"EQUALIZATION: WAIT",
    49:"EMERGANCY CHARGE: ERROR",
    50:"MAN. EQUALIZATION: WAIT",
    51:"MAN. EQUALIZATION: ERROR",
    52:"MAN: EQUALIZATION: READY",
    53:"AUTO. DESULFATATION: WAIT",
    54:"ABSORPTION PHASE",
    55:"DC-SWITCH OFF",
    56:"PEAK-SHAVING: WAIT",
    57:"ERROR BATTERY INVERTER",
    58:"NPU-ERROR",
    59:"BMS OFFLINE",
    60:"MAINTENANCE CHARGE ERROR",
    61:"MAN. SAFETY CHARGE ERROR",
    62:"SAFETY CHARGE ERROR",
    63:"NO CONNECTION TO MASTER",
    64:"LITHIUM SAFE MODE ACTIVE",
    65:"LITHIUM SAFE MODE DONE",
    66:"BATTERY VOLTAGE ERROR",
    67:"BMS DC SWITCHED OFF",
    68:"GRID INITIALIZATION",
    69:"GRID STABILIZATION",
    70:"REMOTE SHUTDOWN",
    71:"OFFPEAK-CHARGE",
    72:"ERROR HALFBRIDGE",
    73:"BMS: ERROR OPERATING TEMPERATURE",
    74:"FACOTRY SETTINGS NOT FOUND",
    75:"BACKUP POWER MODE - ACTIVE",
    76:"BACKUP POWER MODE - BATTERY EMPTY",
    77:"BACKUP POWER MODE ERROR",
    78:"INITIALISING",
    79:"INSTALLATION MODE",
    80:"GRID OFFLINE",
    81:"BMS UPDATE NEEDED",
    82:"BMS CONFIGURATION NEEDED",
    83:"INSULATION TEST",
    84:"SELFTEST",
    85:"EXTERNAL CONTROL",
    86:"ERROR: TEMPERATURESENSOR",
    87:"GRID OPERATOR: CHARGE PROHIBITED",
    88:"GRID OPERATOR: DISCHARGE PROHIBITED",
    89:"SPARE CAPACITY",
    90:"SELFTEST ERROR",
    91:"EARTH FAULT",
};

var system_type_name =
 {
    0: "Senec Home 8.0 / Pb",
    1: "Senec Business 30.0 / Pb",
    2: "Solarinvert Storage 10.0 / Pb",
    3: "Senec Home 4.0 / Pb",
    4: "Senec Home 5.0/7.5/10.0 / Lithium",
    5: "Senec Home 15.0 / Lithium",
    6: "Senec Business 25.0 / Lithium",
    7: "Senec Home 6.0 Pb",
    8: "Senec Home 10.0 Pb",
    9: "Senec Home V2 5.0/7.5/10.0",
    11: "Senec Home V2 10.0 / Pb",
    12: "OEM LG",
    13: "Senec Business V2_2ph / Lithium",
    14: "Senec Business V2 3ph / Lithium",
    15: "Senec Home V2.1 1ph / Lithium",
	16: "ADS Tec",
    17: "SENEC.Home V3 hybrid",
    18: "SENEC.Home V3 hybrid duo",
    19: "SENEC.Home V3 hybrid",
};

var batt_type_name = {
    0: "Studer Xtender",
    1: "SenecBatt",
    2: "Senec.Inverter V2",
    3: "SENEC.Inverter V2.1",
    4: "SENEC.Inverter V3 LV"
};

var pwr_unit_type_name = {
    0: "N/A",
    1: "Solarinvert SHKW",
    2: "SENEC.Heat"
};

var wallbox_adress_name = "Address";

var wallbox_unknown_hw_type = "unknown";

var wallbox_state_name = {
    0xA1: "Waiting for EV",
    0xB1: "EV is asking for charging",
    0xB2: "EV has the permission to charge",
    0xC2: "EV is charged",
    0xC3: "C2 w. reduced current (error F16, F17)",
    0xC4: "C2 w. reduced current (imbalance F15)",
    0xE0: "Charging point disabled by enable input or update",
    0xE1: "production test",
    0xE2: "EVCC can be programmed",
    0xE3: "Bus idle",
    0xF1: "Unintended closed contact (Welding)",
    0xF2: "Internal error",
    0xF3: "DC residual current detected",
    0xF4: "Upstream communication timeout",
    0xF5: "Lock of socket failed",
    0xF6: "CS out of range",
    0xF7: "State D requested by EV",
    0xF8: "CP out of range",
    0xF9: "Overcurrent detected",
    0xF10: "Temperature outside limits",
    0xF11: "Unintended opened contact",
    0xF12: "Reserved State",
    0xF13: "Reserved State",
};

var pwr_unit_status_enum = {
    0: "Overcurrent",
    1: "Overtemperature",
    2: "Temperature value T1 faulty",
    3: "Temperature value Fehlerhaft T2 faulty",
    9: "Error power meter",
    10: "Connection Error",
    11: "Load-Detection Errorn",
    12: "Watertemperature too warm",
    13: "Hardware error",
    14: "Hardware temperature error",
    15: "Watertemperature too low",
    16: "Sensorcount error",
    17: "Main switch Off"
};

var enfluri_name = {
    0: "N/A",
    1: "METER&nbsp;-&nbsp;GRID:",
    2: "METER&nbsp;-&nbsp;CONSUMPTION:",
    3: "METER&nbsp;-&nbsp;GENERATION:"
};

var OnOff_lang = {
    0: "Off",
    1: "On"
};

var NoneAvailable_lang = {
    0: "No",
    1: "Present"
};

var feature_state = {
    0: "Locked",
    1: "Acquired"
};

var condition_state = {
	0: "Not passed",
	1: "Passed"
};

var battery_state = {
	"EMPTY": "Empty/Offline",
	"ERROR": "Error",
	"OK": "OK"
};

var BatteryPhase = {
    0: "None",
    1: "Constant current",
    2: "Constant voltage",
    3: "Equalization",
    4: "Floating",
    5: "Reduced Floating",
    6: "Periodic constant voltage"
};

var TimeZoneArray = {
	"Europe/Berlin": "Europe/Berlin",
	"Europe/Rome": "Europe/Rome",
	"Europe/Vienna": "Europe/Vienna",
	"Europe/Zurich": "Europe/Zurich",
	"Europe/Paris": "Europe/Paris",
	"Europe/Amsterdam": "Europe/Amsterdam",
	"Europe/Brussels": "Europe/Brussels",
	"Australia/Perth": "Australia/Perth",
	"Australia/Darwin": "Australia/Darwin",
	"Australia/Adelaide": "Australia/Adelaide",
	"Australia/Brisbane": "Australia/Brisbane",
	"Australia/Sydney": "Australia/Sydney",
	"Australia/Hobart": "Australia/Hobart",
	"Australia/Melbourne": "Australia/Melbourne",
	"Europe/London": "Europe/London"
};

var CEI_Status = {
	0: "Max voltage",
	1: "Min voltage",
	2: "Temperature",
	3: "Grid current",
	4: "Special charge",
	8: "CEI Startup",
	9: "Overfrequency",
	10: "Stabilization"
};

var SysUpdateState = {
    0: "Logging systemboot to server",
    1: "Waiting for next request",
    2: "Reporting status to server",
    3: "Controller-software Download",
    4: "Checksum Download",
    5: "Checksum Validation",
    6: "GUI Download",
    7: "Checksum Download",
    8: "Checksum Validation & Extracting GUI",
    9: "System Reboot - Reload page in 60 seconds."
};

var bms_status_enum = {
    4: "CapacityAlarm",
    5: "FullyCharged",
    6: "BatteryInstalled",
    7: "CommunicationFailure",
    8: "TerminateDischarge",
    9: "TerminateCharge",
    10: "OverDischargeAlarm",
    11: "OverChargeAlarm",
    12: "TemperatureProtectionCharge",
    13: "TemperatureProtectionDischarge",
    14: "OverCurrentCharge",
    15: "OverCurrentDischarge"
};

var CountryCodeArray = {
	"de": "Germany",
	"it": "Italy",
	"au": "Australia",
	"at": "Austria",
	"gb": "Great Britain",
	"ch": "Switzerland",
	"fr": "France",
	"be": "Belgium",
	"nl": "Netherlands"
};

var inverterNames = {
    "INV_LV": "SENEC.Home V3 LV Inverter",
    "INV_HV": "SENEC.Home V3 HV Inverter",
};

var Samsung_Wizard = {
	"confirmInternalCan": "Please confirm the white patch cable is plugged into the port on battery module A marked black.",
	"clickConfirm": "Please confirm the dialog by pressing \"Start\".",
	"scanningModules": "Scanning for modules...",
	"detectedModuleCount": "Number of detected modules:",
	"checkModuleCount": "Please check the number of detected battery modules and press \"Confirm\".",
	"noModulesDetected": "No modules detected!",
	"moduleCountIncorrect": "If the number of detected modules is incorrect:",
	"checkWiring": "Please check the wiring of patch cables and wake-up cable on battery module A.",
	"restartScanning": "Repeat scanning for battery modules by pressing \"Restart\".",
	"changeToExternalCan": "Please plug the white patch cable into the white port on battery module A.",
	"waitForExternalCan": "Afterwards please allow some seconds for the connection to establish.",
	"waitForInverter": "Starting up inverter...",
	"equalCharging": "Equalizing state of charge of battery modules...",
	"testCharging": "Performing test charge...",
	"chargingFailed": "Test charge failed!",
	"checkPowerPlugs": "Please check power cables.",
	"wizardDone": "Wizard done.",
	"finishWizard": "Installation done. Press \"Finish\" to proceed.",
	"abortWizard": "Alert: The battery wizard must be completed successfully in order to complete the installation."
};
