/** Prevent JSHint warning about functions called from HTML sites. */
/* exported casc_enum, lng, tooltip system_state_name, tooltip, system_state_name,
system_type_name, batt_type_name, pwr_unit_type_name, pwr_unit_status_enum, enfluri_name,
OnOff_lang, NoneAvailable_lang, feature_state, condition_state, battery_state,
BatteryPhase, TimeZoneArray, CEI_Status, SysUpdateState, bms_status_enum,
CountryCodeArray, Country_enum, BMZ_WizardState, wallbox_adress_name, wallbox_unknown_hw_type,
wallbox_state_name, inverterNames, Samsung_Wizard */

var lng = {
	"TODAY": "OGGI",
	"YESTERDAY": "IERI",
	"WEEK": "SETTIMANA",
	"MONTH": "MESE",
	"YEAR": "ANNO",
	"OVERALL": "TOTALE",
	"LAST24": "ULTIME 24H",
	"Status_houseConsumption": "UTILIZZO DOMESTICO",
	"Status_batteryCharge": "CARICA ACCUMULATORE",
	"Status_gridImport": "CONSUMO DA RETE",
	"Status_pvGenerated": "ENERGIA FV PRODOTTA",
	"Status_batteryDischarge": "CONSUMO DA ACCUMULATORE",
	"Status_gridExport": "IMMISSIONE NELLA RETE",
	"Status_PU0": "1. RISCALDATORE",
	"Status_PU1": "2. RISCALDATORE",
	"Status_PU2": "3. RISCALDATORE",
	"Status_PU3": "4. RISCALDATORE",
	"Status_PU4": "5. RISCALDATORE",
	"Status_PU5": "6. RISCALDATORE",
	"USERNAME": "NOME UTENTE",
	"PASSWORD": "PASSWORD",
	"Logout": "Esci",
	"Save": "Salva",
	"Delete": "Cancella",
	"Close": "Chiudi",
	"Next": "Avanti",
	"Previous": "Indietro",
	"Check": "Controllare",
	"SPSSTOP": "STOP",
	"ERROR": "ERRORE",
	"CHECK_INTERNET_RESULT_OK": "OK",
	"CHECK_INTERNET_RESULT_CHECK": "Verifica...",
	"CHECK_INTERNET_RESULT_NONE": "Errore!",
	"ALERT_ERROR": "Errore! ",
	"WIZARD_ERROR_EULA": "È necessario accettare le condizioni della licenza!",
	"WIZARD_CHECK_FIELDS_ERROR": "I campi contrassegnati in rosso devono essere compilati e verificati!",
	"WIZARD_CHECK_LOGIN_ERROR": "Indirizzo e-mail o la password sbagliata. Si prega di verificare.",
	"WIZARD_CHECK_LOGIN_BUTTON": "Accedi come installatore.",
	"WIZARD_CHECK_LOGIN_SUCCESS": "Accesso effettuato. ",
	"WIZARD_CHECK_LOGIN_CONTRACTOR": "Seleziona il livello di Partnership, se disponibile.",
	"WIZARD_CHECK_PASSWORD_FIELD_ERROR_SHORT": "È necessario inserire una password con almeno 8 caratteri!",
	"WIZARD_CHECK_PASSWORD_FIELD_ERROR_NO_MATCH": "Le password immesse non corrispondono!",
	"WIZARD_CHECK_EMAIL_FIELD_ERROR_NO_MATCH": "Gli indirizzi e-mail immessi non corrispondono!",
	"WIZARD_CHECK_EMAIL_FIELD_ERROR_VALIDATION": "L'indirizzo e-mail deve avere un formato valido, ad es.: mariorossi@esempio.it!",
	"WIZARD_CHECK_EMAIL_FIELD_ERROR_SAME_INSTALLER_CUSTOMER": "Gli indirizzi e-mail dell’installatore e del proprietario non possono essere identici!",
	"WIZARD_CHECK_SENEC_SERIAL_FIELD_ERROR_VALIDATION": "Il numero di serie SENEC corrisponde ad un formato valido.",
	"WIZARD_CHECK_CONFIRMATION_ERROR_CHECK_ALL": "È necessario selezionare tutti i punti apponendo un segno di spunta e correggere i campi!",
	"WIZARD_CHECK_BATTERY_PHASE_ERROR": "La fase dell'accumulatore a batteria deve corrispondere a quella di almeno un inverter attivo, oppure almeno un inverter attivo deve essere trifase! Modificare le impostazioni avanzate.",
	"WIZARD_CHECK_BATTERY_NEED_PHASE": "È necessario selezionare una fase della batteria!",
	"WIZARD_INVERTERS_METER_HOUSE_CHECK": "Se non si attiva il wattmetro per l'abitazione (direzione flusso 2 o 3), è necessario attivare almeno un inverter fotovoltaico!",
	"WIZARD_NOTIFY_NO_CONN_TO_MCU": "ATTENZIONE: Nessuna connessione al dispositivo SENEC. Il processo di configurazione non può essere portato a termine! Verificare che non siano presenti errori di connessione!",
	"WIZARD_CHECK_PV_MAX_POWER": "Potenza fotovoltaica registrato deve essere maggiore di 0!",
	"WIZARD_CHECK_IP_ADDRESS": "Inserisci un corretto indirizzo IP!",
	"WIZARD_CHECK_PU_MAX_POWER": "Inserisci un valore positivo di max 2000W per fase!",
	"WIZARD_CHECK_PU_TOTAL_POWER": "Inserire tutti i valori di potenza!",
	"WIZARD_CHECK_PU_MIN_TEMP": "Temperatura minima deve essere inferiore alla temperatura massima!",
	"WIZARD_CHECK_PU_TEMP_RANGE": "Ci deve essere selezionata una temperature en el intervallo valido.",
	"WIZARD_CHECK_GRID_CONNECTION": "Si prega di selezionare il tipo di connessione di rete!",
	"WIZARD_CHECK_ENFLURI": "Si prega di selezionare una casella di controllo per la configurazione del sensore di flusso direzione potere!",
	"WIZARD_CHECK_TIMEZONE": "Ci deve essere selezionato un fuso orario.",
	"WIZARD_CHECK_POS_DECIMAL": "Ci deve essere un numero positivo da specificare.",
	"WIZARD_CHECK_RS485": "Gli indirizzi non devono essere gli stessi.",
	"WIZARD_CHECK_SERIAL": "Numero di serie non valido.",
	"WIZARD_CHECK_PERCENTAGE": "Denovo essere 0-100%.",
	"WIZARD_CHECK_PV_POWER": "La potenza di picco deve essere di almeno 100W.",
	"WIZARD_EG_ERROR_NEED_INITIAL_CONFIG": "Prima di iscriversi ad Econamic Grid è necessario configurare la memoria del dispositivo SENEC con l'assistente di configurazione.",
	"WIZARD_GRID_ERROR_NEED_INITIAL_CONFIG": "È necessario prima configurare la memoria SENEC con la 'Configurazione guidata' prima di poter impostare i parametri di rete!",
	"WIZARD_EG_CHECK_FIELDS_ERROR": "I campi contrassegnati in rosso devono essere compilati e verificati!",
	"WIZARD_EG_ERROR_EULA": "Errore! È necessario accettare le Condizioni generali di contratto e le condizioni contrattuali e confermare l'informativa sul diritto di recesso. Selezionare inoltre i tipi di energia di bilanciamento!",
	"WIZARD_EG_CHECK_EMAIL_FIELD_ERROR_NO_MATCH": "Gli indirizzi e-mail immessi non corrispondono!",
	"WIZARD_EG_CHECK_EMAIL_FIELD_ERROR_VALIDATION": "L'indirizzo e-mail deve avere un formato valido, ad es.: marioesempio@esempio.it!",
	"WIZARD_EG_CHECK_DEBIT_AUTHORITY_ERROR": "Accettare l'autorizzazione permanente di addebito in conto corrente!",
	"WIZARD_EG_CHECK_CONFIRMATION_ERROR_CHECK_ALL": "È necessario selezionare tutti i punti apponendo un segno di spunta e correggere i campi!",
	"WIZARD_EG_ERROR_NO_POWERMETER_SERIAL": "Impossibile rilevare il numero del contatore!",
	"WIZARD_EG_TEST_INSTALLATION_PENDING": "test in corso...",
	"WIZARD_EG_TEST_INSTALLATION_RESULT_ERROR": "Errore!",
	"WIZARD_EG_TEST_INSTALLATION_POWERMETER_COM_OK": "OK!",
	"WIZARD_EG_TEST_INSTALLATION_POWERMETER_READ_OK": "OK!",
	"WIZARD_EG_TEST_INSTALLATION_SWITCH_COM_OK": "OK!",
	"WIZARD_EG_TEST_INSTALLATION_NO_RESULTS": "Non è stato possibile eseguire alcuni test! Verificare la comunicazione con il controllo SENEC e la presenza di errori di installazione! In seguito, eseguire nuovamente il test cliccando sul pulsante 'Avvia test'",
	"WIZARD_EG_TEST_INSTALLATION_ERRORS": "Si sono verificati errori durante i test delle funzioni di Econamic Grid. Verificare l'installazione dell'armadio del contatore di Econamic Grid e la connessione dei cavi. In seguito, eseguire nuovamente il test cliccando sul pulsante 'Avvia test'",
	"WIZARD_EG_NO_INTERNET": "ATTENZIONE: nessuna connessione a Internet! Stabilire una connessione stabile a Internet!",
	"WIZARD_EG_SUBMIT_NO_INTERNET": "ATTENZIONE: la connessione a Internet è stata interrotta. È necessario stabilire una connessione stabile a Internet. In seguito, avviare nuovamente l'assistente Econamic Grid e ripetere la procedura di configurazione di Econamic Grid!",
	"YES": "Sì",
	"NO": "No",
	"NOT_POSSIBLE": "Impossibile",
	/*User Definitions*/
	"OWNER": "Proprietario",
	"INSTALLER": "Installatore",
	"MANUFACTURER": "Quadrista",
	"SUPERUSER": "Superuser",
	"TESTER": "Tester",
	"UNKNOWN": "Sconosciuto",
	/*stat0 Page*/
	"HOMECONSUMPTION": "UTILIZZO DOMESTICO",
	"BATTERYCHARGE": "CARICA",
	"GRIDIMPORT": "PRELIEVO DA RETE",
	"PVGENERATED": "ENERGIA FV PRODOTTA",
	"BATTERYDISCHARGE": "SCARICA",
	"GRIDEXPORT": "IMMISSIONE IN RETE",
	/*index.html*/
	"lStatus": "STATO",
	"lKonfiguration": "IMPOSTAZIONI",
	"lSetup": "CONFIGURAZIONE",
	/*Headings*/
	"lDateTime": "DATA/ORA",
	"lPowerSockets": "PRESE",
	"lInformation": "INFORMAZIONI",
	"lBatteryMaintenance": "MANUTENZIONE",
	"lStartTest": "AVVIO E TEST",
	"lHeatingRod": "RISCALDATORE",
	"lAccumulatorHeader": "ACCUMULATORE",
	"lAutarkyHeader": "AUTARCHIA",
	"lPeakShaving": "PEAK-SHAVING",
	"lSelftest" : "AUTOTEST",
	/*konfInf.html*/
	"lOperatingHours": "ORE OPERATIVE (h):",
	"lLastMaintenance": "ULTIMA MANUTENZIONE (d):",
	"lType": "TIPO :",
	"lState": "STATO:",
	"lNextState": "STATO RITARDATO:",
	"lMCUID": "SER.UNIT.CONTROLLO:",
	"lMACADDRESS": "INDIRIZZO MAC:",
	"lSystem": "CONTROLLO:",
	"lFrequency": "FREQUENZA (Hz):",
	"lVoltage": "TENSIONE (V):",
	"lCurrent": "CORRENTE (A):",
	"lPower": "POTENZA (W):",
	"lTotalPower": "POTENZA COMPLESSIVA (W):",
	"lAccu": "ACCUMULATORE:",
	"lPowerValues": "VALORI POTENZA:",
	"lBatteryPower": "POTENZA BATTERIA (W):",
	"lBatteryVoltage": "TENSIONE BATTERIA (V):",
	"lBatteryCurrent": "CORRENTE BATTERIA (A):",
	"lBatteryCurrentEach": "INTENSITÀ BATTERIA (A) PER INVERTER:",
	"lMaxCapacity": "CAPACITÀ MAX. (Ah):",
	"lFuelGauge": "LIVELLO (%):",
  "lAcApparentPower": "POTENZA APPARENTE (VA):",
  "lAcActivePower": "POTENZA ATTIVA (W):",
  "lAcReactivePower": "POTENZA REATTIVA (VAr):",
	"lTotalCharge": "CARICA COMPLESSIVA (kWh):",
	"lNoDesulfatCharge": "CARICO DI SOLFATO:",
	"lBattInverterType": "TIPO INVERTER :",
	"lInv1Temp": "TEMP. INVERTER 1 (°C):",
	"lInv2Temp": "TEMP. INVERTER 2 (°C):",
	"lInv3Temp": "TEMP. INVERTER 3 (°C):",
	"lNoLiModule": "QUANTITÀ MODULI Li:",
	"lInverterPhase": "FASE DI CARICA:",
	"lTimeRemainEqual": "LIVELLAMENTO DURATA RESTANTE (min):",
	"lTimeRemainCharge": "CARICA DURATA RESTANTE (min):",
	"lDurationCharge": "DURATA CARICA COMPLESSIVA (min):",
	"lHomeconsumption": "UTILIZZO DOMESTICO (W):",
	"lPVGeneration": "PRODUZIONE FV (W):",
	"lPVLimit": "LIMITAZIONE FV (%):",
	"lMpp0Generation":"PRODUZIONE MPP 1",
	"lMpp1Generation":"PRODUZIONE MPP 2",
	"lMpp2Generation":"PRODUZIONE MPP 3",
	"lUnbalancedLoadLimit": "SBILANCIAMENTO:",
	"lExportLimit": "LIMITAZIONE IMMISSIONE:",
	"lVoltageLimit": "LIMITAZIONE TENSIONE:",
	"lCapacityTestValue": "TEST CAPACITÀ (Wh):",
	"lIslandMode": "FUNZIONAMENTO ISOLATO:",
	"lPUConTotal": "PU-CONSUMO (W):",
	"lFeaturePackage": "PACCHETTI AGGIUNTIVI:",
	"lFeatureIsland": "FUNZIONAMENTO ISOLATO:",
	"lFeatureIslandPro": "FUNZIONAMENTO ISOLATO PRO:",
	"lFeatureSockets": "PRESE:",
	"lFeatureHeatBox": "RISCALDATORE:",
	"lFeaturePeakShaving": "PEAK-SHAVING:",
	"lFeatureEcoGrid": "ECONAMIC-GRID:",
	"lFeatureCloud": "SENEC.CLOUD:",
	"lFeatureCar": "STAZIONE DI CARICO:",
	"lCEIStatus": "STATO PARAMETRI DI CONTROLLO DI POTENZA (CEI)",
	"lFeatureSHKW": "SOLARINVERT SHKW:",
	"lFeatureSGready": "SG-READY:",
	/*accu0.html*/
	"lCapacity": "CAPACITÀ (%):",
	/*AccuTest.html*/
	"lAccuStartTest": "AVVIO E TEST ACCUMULATORE",
	"lStopInitialCharge": "STOP<br>PRIMA CARICA",
	"lStartInitialCharge": "AVVIO<br>PRIMA CARICA",
	"lInitialChargeNotStarted": "Prima carica non avviata...",
	"lInitialChargeFinished": "Prima carica terminata...",
	"lInitialChargeAborted": "Prima carica interrotta...",
	"lInitialChargeStarted": "Prima carica avviata...",
	"lInitialCharge10minCharge": "Prova di polarità (carica 10 min.)",
	"lInitialCharge10minChargeLI": "Caricare per 10 min.",
	"lInitialCharge5minDischarge": "Prova di polarità (scaricamento 5 min.)",
	"lInitialCharge5minDischargeLI": "Scarica 5 min.",
	"lInitialChargeHint1_0": "Differenza di tensione tra corrente di carica e di scarica (V): ",
	"lInitialChargeHint1_1": "<br>Corrente massima di carica (A): ",
	"lInitialChargeHint1_2": "<br>Corrente massima di scarica (A): ",
	"lInitialChargeHint1_3": "<br>Avviso: durante i prossimi 5 minuti della fase di scaricamento, controllare se l'aerazione dell'inverter della batteria è attivata.",
	"lInitialChargeHint1_4": "<br><button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Confermare</p></button>\n\<button id=InitChargeAckbtn onclick='InitChargeRerun();'><p>Ripeti</p></button>\n",
	"lInitialCharge5minTest": "Test del connettore dei poli (scaricamento 5 min.)",
	"lInitialChargeQuestionSenecBatt": "<p>Verificare che il connettore dei poli non sia surriscaldato.</p><br>\n<p>L'aerazione dell'inverter della batteria era attivo?</p><br>\n<button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Confermare</p></button>\n\<button id=InitChargeAckbtn onclick='InitChargeRerun();'><p>Ripetere</p></button>",
	"lInitialChargeQuestionOther": "<p>Verificare che il connettore dei poli non sia surriscaldato.</p><br>\n<button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Confermare</p></button>\n\<button id=InitChargeAckbtn onclick='InitChargeRerun();'><p>Ripetere</p></button>",
	"lInitialChargeFullCharge": "Carica completa conclusiva...",
	"lInitialChargeDone": "Completato",
	"lInitialChargeFinalHintPB": "<p>Prima carica completata. La modalità Island può essere sbloccata.</p><br>\n<button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Confermare</p></button>",
	"lInitialChargeFinalHintLI": "<p>Prima carica completata. La modalità Island può essere sbloccata.</p><br>\n<p>Assicurarsi che sia stata aggiunta l'acqua.</p><br>\n<button id=InitChargeAckbtn onclick='InitialChargeAck();'><p>Confermare</p></button>",
	"lInitialChargeUnknownState": "Stato sconosciuto",
	"lInitialChargeStep1": "CARICA 10 min",
	"lInitialChargeStep2": "SCARICA 5 min",
	"lInitialChargeStep3": "ESITO",
	"lInitialChargeStep4": "SCARICA 5 min",
	"lInitialChargeStep5": "ESITO",
	"lInitialChargeStep6": "CARICA COMPLETA",
	"lInitialChargeProtokoll": "PROTOCOLLO TEST:",
	"lInitialChargeState": "Prima carica:",
	"lInitialChargeMinVoltage": "Tensione minima (V):",
	"lInitialChargeMaxVoltage": "Tensione massima (V):",
	"lInitialChargeVoltageDiff": "Differenza di tensione (V):",
	"lInitialChargeMaxChargeCurrent": "Massima corrente di carica (A):",
	"lInitialChargeMaxDischargeCurrent": "Massima corrente di scarica (A):",
	"lInitialChargeCurrent": "Corrente attuale (A):",
	"lInitialChargeVoltage": "Tensione attuale (V):",
	"lInitialChargeWaterRefill": "Aggiungere acqua?",
	"lInitialChargeFuelGauge": "Livello della batteria (%):",
	"lInitialChargeStartCriteria": "Il livello della batteria deve essere inferiore al 90%.",
	/*ksockets.html*/
	"lSocketsPowerStateOn": "On",
	"lSocketsPowerStateOff": "Off",
	"lSocketsLabel": "Prese",
	"lSocketsSocketTop": "Presa ",
	"lSocketsPermanentOn": "Ttivo In Permanenza:",
	"lSocketsActivateAuto": "Attivazione Automatica:",
	"lSocketsPowerOn": "Turn-on Threshold (W):",
	"lSocketsPowerOff": "Turn-off Threshold (W):",
	"lSocketsExcessDuration": "Urata Carica In Eccesso (min):",
	"lSocketsDuration": "Durata Presa On (min):",
	"lSocketsPeriodDuration": "Periodo Di Attivazione (min):",
	"lSocketsSocketBottom": "Presa",
	"lSocketsState": "Stato:",
	"lSocketsRemainTime": "Tempo RimanentE (min):",
	"lSocketsSave": "Salva",
	"lSocketsActivateTime" : "Attiva Il Tempo",
	"lSocketsTime" : "Tempo Di Commutazione (HH:MM)",
	"lSocketsAlreadySwitched": "Già Acceso:",

	/*login.html*/
	"lLoginLabel": "LOGIN",
	"lLoginHint": "PER ACCEDERE È NECESSARIO DISPORRE DI UNA PASSWORD",
	"lLoginUser": "UTENTE:",
	"lLoginPassword": "PASSWORD:",
	"lLoginSignIn": "REGISTRAZIONE",
	/*power_unit_info.html*/
	"lPWRUTitle0": "Unità di regolazione della potenza:",
	"lPWRUState0": "STATO:",
	"lPWRUPowerEach0": "POTENZA PER FASE (W):",
	"lPWRUPowerTotal0": "POTENZA TOTALE (W):",
	"lPWRUTempMin0": "TEMPERATURA MIN:",
	"lPWRUTempMax0": "TEMPERATURA MAX:",
	"lPWRUTempMin_Now0": "TEMPERATURA EFFETTIVA MIN:",
	"lPWRUTempMax_Now0": "TEMPERATURA EFFETTIVA MAX:",
	"lPWRURev0": "REVISIONE:",
	"lPWRUTitle1": "Unità di regolazione della potenza:",
	"lPWRUState1": "STATO:",
	"lPWRUPowerEach1": "POTENZA PER FASE (W):",
	"lPWRUPowerTotal1": "POTENZA TOTALE (W):",
	"lPWRUTempMin1": "TEMPERATURA MIN:",
	"lPWRUTempMax1": "TEMPERATURA MAX:",
	"lPWRUTempMin_Now1": "TEMPERATURA EFFETTIVA MIN:",
	"lPWRUTempMax_Now1": "TEMPERATURA EFFETTIVA MAX:",
	"lPWRURev1": "REVISION:",
	"lPWRUTitle2": "Unità di regolazione della potenza:",
	"lPWRUState2": "STATO:",
	"lPWRUPowerEach2": "POTENZA PER FASE (W):",
	"lPWRUPowerTotal2": "POTENZA TOTALE (W):",
	"lPWRUTempMin2": "TEMPERATURA MIN:",
	"lPWRUTempMax2": "TEMPERATURA MAX:",
	"lPWRUTempMin_Now2": "TEMPERATURA EFFETTIVA MIN:",
	"lPWRUTempMax_Now2": "TEMPERATURA EFFETTIVA MAX:",
	"lPWRURev2": "REVISION:",
	"lPWRUTitle3": "Unità di regolazione della potenza:",
	"lPWRUState3": "STATO:",
	"lPWRUPowerEach3": "POTENZA PER FASE (W):",
	"lPWRUPowerTotal3": "POTENZA TOTALE (W):",
	"lPWRUTempMin3": "TEMPERATURA MIN:",
	"lPWRUTempMax3": "TEMPERATURA MAX:",
	"lPWRUTempMin_Now3": "TEMPERATURA EFFETTIVA MIN:",
	"lPWRUTempMax_Now3": "TEMPERATURA EFFETTIVA MAX:",
	"lPWRURev3": "REVISION:",
	"lPWRUTitle4": "Unità di regolazione della potenza:",
	"lPWRUState4": "STATO:",
	"lPWRUPowerEach4": "POTENZA PER FASE (W):",
	"lPWRUPowerTotal4": "POTENZA TOTALE (W):",
	"lPWRUTempMin4": "TEMPERATURA MIN:",
	"lPWRUTempMax4": "TEMPERATURA MAX:",
	"lPWRUTempMin_Now4": "TEMPERATURA EFFETTIVA MIN:",
	"lPWRUTempMax_Now4": "TEMPERATURA EFFETTIVA MAX:",
	"lPWRURev4": "REVISION:",
	"lPWRUTitle5": "Unità di regolazione della potenza:",
	"lPWRUState5": "STATO:",
	"lPWRUPowerEach5": "POTENZA PER FASE (W):",
	"lPWRUPowerTotal5": "POTENZA TOTALE (W):",
	"lPWRUTempMin5": "TEMPERATURA MIN:",
	"lPWRUTempMax5": "TEMPERATURA MAX:",
	"lPWRUTempMin_Now5": "TEMPERATURA EFFETTIVA MIN:",
	"lPWRUTempMax_Now5": "TEMPERATURA EFFETTIVA MAX:",
	"lPWRURev5": "REVISION:",
	"lPWRUNoConfig": "Unità di regolazione della potenza non configurato!",
	/*wallbox_info.html*/
	"lWallboxTitle0": "Wallbox 1:",
	"lWallboxTitle1": "Wallbox 2:",
	"lWallboxTitle2": "Wallbox 3:",
	"lWallboxTitle3": "Wallbox 4:",
	"lWallboxMaxCurrent0": "CORRENTE MAX. (A):",
	"lWallboxMaxCurrent1": "CORRENTE MAX. (A):",
	"lWallboxMaxCurrent2": "CORRENTE MAX. (A):",
	"lWallboxMaxCurrent3": "CORRENTE MAX. (A):",
	"lWallboxState0": "STATO:",
	"lWallboxState1": "STATO:",
	"lWallboxState2": "STATO:",
	"lWallboxState3": "STATO:",
	"lWallboxTotalPower0": "POTENZA TOTALE (VA):",
	"lWallboxTotalPower1": "POTENZA TOTALE (VA):",
	"lWallboxTotalPower2": "POTENZA TOTALE (VA):",
	"lWallboxTotalPower3": "POTENZA TOTALE (VA):",
	"lWallboxRevision0": "REVISIONE:",
	"lWallboxRevision1": "REVISIONE:",
	"lWallboxRevision2": "REVISIONE:",
	"lWallboxRevision3": "REVISIONE:",
	"lWallboxHardware0": "TIPO PCBA:",
	"lWallboxHardware1": "TIPO PCBA:",
	"lWallboxHardware2": "TIPO PCBA:",
	"lWallboxHardware3": "TIPO PCBA:",
	"lWallboxCurrent0": "CORRENTE PER FASE (A):",
	"lWallboxCurrent1": "CORRENTE PER FASE (A):",
	"lWallboxCurrent2": "CORRENTE PER FASE (A):",
	"lWallboxCurrent3": "CORRENTE PER FASE (A):",
	"lWallboxNoConfig": "Wallbox non configurato!",
	/*ksetup1.html*/
	"lSetupBatteryVoltage": "Tensione batteria (V)",
	"lSetupBatteryCurrent": "Corrente batteria (A)",
	"lSetupNumDesulfatCharges": "Cariche smaltimento solfato",
	"lSetupBatteryTemp": "Temperatura batteria (°C)",
	"lSetupCaseTemp": "Temperatura alloggiamento (°C)",
	"lSetupServerConnectionState": "Connessione server",
	"lSetupBatteryInverterConnectionState": "Inverter batteria",
	"lSetupPowerMeter1ConnectionState": "Wattmetro 1",
	"lSetupPowerMeter2ConnectionState": "Wattmetro 2 ",
	"lSetupPVConnectionState": "Inverter fotovoltaico",
	"lSetupPWRUnitConnectionState": "Power Unit",
	"lSetupMasterConnectionState": "Connessione master",
	"lSetupNumConnectedSlaves": "Slave collegati:",
	"lSetupEGSwitchConnectionState": "Commutatore EG",
	"lSetupIskraConnectionState": "Contatore Iskra",
	"lSetupPS1": "Presa 1",
	"lSetupPS2": "Presa 2",
	"lSetupPump": "Pompa",
	"lSetupXCOM": "Xcom",
	"lSetupFAN": "Aerazione",
	"lSetupAutoCycle": "Ciclo automatico",
	"lSetupSetTime": "Impostare l'ora",
	"lSetupReset": "Ripristinare:",
	"lSetupResetStatistics": "Statistiche globali",
	"lSetupSetBatteryProtection": "Modalita  protezione accumulatore",
	"lSetupPauseSpecial": "Sospendi il carico speciale",
	"lSetupUseInternet": "Utilizzare Internet",
	"lSetupFWUpdate": "Aggiornamento software",
	"lSetupNAUpdate": "Update SENEC.NSP dalla scheda SD",
	"lSetupOverwriteFeatures": "Sbloccare funzionalità aggiuntive",
	"lSetupConfigWizard": "Assistente di configurazione",
	"lSetupEGWizard": "Iscrizione ad Econamic Grid",
	"lSetupRestartMCU": "Riavviare il dispositivo",
	"lSetupCapacityTest": "Test capacità ",
	"lSetupTestPower": "Potenza test (W)",
	"lSetupCharge": "Caricare",
	"lSetupdDischarge": "Scaricare",
	"lSetupTestPowerError": "Il valore dell'intensità per il test non può essere vuoto! ",
	"lSetupUpdateAvailable": "Aggiornamento disponibile.",
	"lSetupNoUpdateAvailable": "Attualmente non è disponibile alcun aggiornamento.",
	"lSetupLanguageSelection": "Selezione lingua",
	"lSetupFullWizard": "Aggiornamento guidato",
	"lSetupInverterUpdate": "Aggiornamento inverter dalla scheda SD",
	"lSetupPvWizard" : "FV guidato",
	/*Wizard file*/
	"wizard-file": './wizard_IT.html',
	/*modal.js*/
	"lNoValidIP": ' non è un indirizzo IP valido.',
	"lErrMaxConnPwr": "L'intensità massima del collegamento non può corrispondere a 0.",
	"lErrMaxInvPwr": "La potenza massima dell'inverter non può essere inferiore ad 1 W!",
	"lErrModbusAddr": "Gli indirizzi del Modbus devono essere compresi tra 1 e 254!",
	"lWIZARD_ADDR_SLAVE": "Indirizzo slave:",
	"lWIZARD_ADDR_1": "Indirizzo 1:",
	"lConfirmAccuPole": "Il poli che collega i moduli batteria con le sbarre con una coppia di 5 Nm.",
	/*Konfiguration.AccuService.html*/
	"lAccuServiceWaterRefill": "Carica di manutenzione completata, aggiungere acqua e confermare",
	"lAccuServiceMntRunning": "Carica di manutenzione in corso ...",
	"lAccuServiceMntNeeded": "Manutenzione richiesta, eseguire carica di manutenzione",
	"lAccuServiceFilterNeeded": "Sostituzione filtro richiesta",
	"lAccuServiceFullcharge": "Carica completa",
	"lAccuServiceReleaseDischarge": "Attiva scaricamento",
	"lAccuServiceDesulfatationCharge": "Carica smaltimento solfato",
	"lAccuServiceEqualizationCarge": "Carica di compensazione",
	"lAccuServiceMntCharge": "Carica di manutenzione",
	"lAccuServicePrepareModule": "Sostituzione del modulo",
	"lAccuServiceConfirmFilter": "Conferma sostituzione filtro",
	/*kpeakshaving.html*/
	"lPSerrorPercentage": "La capacità deve essere compresa tra 0 e 100%!",
	"lPSerrorTime": "Verificare il tempo inserito!",
	"lPSActivate": "Attivare il peak shaving",
	"lPSReservoirMsg1": "Quando",
	"lPSReservoirMsg2": "% la carica della batteria è raggiunta, l'energia generata successivamente viene alimentata nella griglia. La batteria verrà ricaricata nuovamente, se viene generata più energia di quanto possa essere alimentato (limite di alimentazione) o l'ora impostata è stata raggiunta.",
	"lPSUntilTime": "ORARIO FINE:",
	"lPSHeader": "CONFIGURAZIONE PEAK SHAVING",
	"lPSSettings": "IMPOSTAZIONE:",
	/*Page Loading*/
	"lLoadPage": "Attendere...",
	/*Package Checker*/
	"true": "Valido",
	"false": "Non valido",
	"confirmed": "Confermato",
	"AKTIVIERUNGSCODE_UNBEKANNT": "Il codice di attivazione è sconosciuto!",
	"AKTIVIERUNGSCODE_VON_ANDERER_STEUEREINHEIT_VERWENDET": "Il codice di attivazione è già in uso da un'altra unità di controllo!",
	"STEUEREINHEIT_BEREITS_MIT_ANDEREM_AKTIVIERUNGSCODE_REGISTRIERT": "Questo sistema è già stato attivato per questa funzione!",
	"lNotActive": "Questa funzione non è abilitata!",
	/*modal.update.html*/
	"lUpdateFWUpdate": "Aggiornamento del software disponibile!",
    "lUpdateRequest": "Vuoi aggiornare il software della MCU?",
	"lUpdateLater": "Più tardi",
	"lUpdateNow": "Aggiorna ora",
	"lUpdateStatus": "Stato dell’aggiornamento:",
	/*09-06-2017
	power_unit_info.html*/
	"lPUmin0": "Minimo [°C]:",
	"lPUmax0": "Massimo [°C]:",
	"lPUSave0": "Salva",
	"lPUmin1": "Minimo [°C]:",
	"lPUmax1": "Massimo [°C]:",
	"lPUSave1": "Salva",
	"lPUmin2": "Minimo [°C]:",
	"lPUmax2": "Massimo [°C]:",
	"lPUSave2": "Salva",
	"lPUmin3": "Minimo [°C]:",
	"lPUmax3": "Massimo [°C]:",
	"lPUSave3": "Salva",
	"lPUmin4": "Minimo [°C]:",
	"lPUmax4": "Massimo [°C]:",
	"lPUSave4": "Salva",
	"lPUmin5": "Minimo [°C]:",
	"lPUmax5": "Massimo [°C]:",
	"lPUSave5": "Salva",
	/*12-06-2017
	wizard*/
	"lWizardPVOnly": "Generazione FV",
	"lWizardMinTempOnly": "Solo controllo della temp.",
	"lWizardPUConnectionError": "Nota: L'impostazione della modalità per l'unità di controllo della potenza è stata impostata su 'Solo generazione FV'!",
	/*19-06-2017
	cei-wizard*/
	"lCEIHeader": "Assistente di CEI",
	"lCEIsyncFreqMax": "Frequenza di riposo - limite superiore [mHz]",
	"lCEIsyncFreqMin": "Frequenza di riposo - limite inferiore [mHz]",
	"lCEIreconnectTime": "Ritardo di inserzione  [s]",
	"lCEIreductionDrop": "Rapporto di riduzione di potenza [1/s]",
	"lCEIcosPhiLockIn": "Potenza attiva lock-in [%]",
	"lCEIcosPhiLockOut": "Potenza attiva lock-out [%]",
	"lCEIstabUpperThresh": "Limitazione di potenza attiva - limite superiore [mHz]",
	"lCEIstabLowerThresh": "Limitazione di potenza attiva - limite inferiore [mHz]",
	"lCEIstabUpperCorner": "Limitazione di potenza attiva - frequenza di cut-off superiore [mHz]",
	"lCEIstabLowerCorner": "Limitazione di potenza attiva - frequenza di cut-off inferiore [mHz]",
	"lCEIactivationDelay": "Ritardo di attivazione [ms]",
	"lCEIvoltageThresh": "Soglia di tensione  [%]",
	"lCEIcosPhiFix": "Fattore di potenza fissato",
	"lCEIcosPhiLabel": "Fattore di potenza",
	/*07-07-2017
	wizard*/
	"lWizardChargePrio1": "Batteria -> Riscaldamento -> Esportazione",
	"lWizardChargePrio2": "Riscaldamento -> Batteria -> Esportazione",
	"lWizardChargePrio3": "Batteria -> Esportazione -> Riscaldamento",
	"lWizardChargePrio4": "Non necessario",
	/*Nulleinspeisung / Volleinspeisung*/
	"lWizardChargePrio1_NoExport": "Batteria -> Riscaldamento",
	"lWizardChargePrio2_NoExport": "Riscaldamento -> Batteria",
	"lSetupGridParameter": "CEI parametro",
    /* konfInf.html */
	"lRevMCU": "REVISIONE MCU:",
	"lRevMCUBL": "REVISIONE MCU-BL:",
	"lRevGUI": "REVISIONE GUI:",
	"lRevNPU": "REVISIONE NPU-REGS:",
	"lRevNPUImage": "REVISIONE NPU-IMAGE:",
	"lRevINV": "REVISIONE INV:",
	"lRevHMI": "REVISIONE HMI:",
	"lRevPU":  "REVISIONE PU:",
	"lRevBDC":  "REVISIONE BDC:",
	"lRevNSP": "REVISIONE NSP:",
	/* OffPeak */
	"lOffPeak_Duration": "TEMPO RESIDUO OFFPEAK (min):",
    /* 30-08-2017
       wizard */
    "lErrAbsoluteFeedInPower": "Il potere di alimentazione non può essere superiore alla generazione.",
    /* 24.10.2017 modal.js */
    "lErrChargePrioNotSelected": "Priorità carica non selezionata!",
    /* 03.11.2017 konfInf.html */
    "lCountryVar": "MODELLO PEASE:",
    /* Alert messages for peakshaving/zero export */
    "lAlertZeroExportActive": "Attenzione: Non è possibile utilizzare Peakshaving se non è consentito l'alimentazione di griglia.",
    "lAlertZeroExportSockets": "Attenzione: i contatti di commutazione possono essere utilizzati solo con l'opzione del periodo di commutazione.",
    "lAlertZeroExportSet": "Attenzione: l'abilitazione dell'esportazione a zero disabilita il picco di salita e consente solo periodi di commutazione per i contatti di commutazione.",
    "lAUVoltWattCharge": "Caricamento modalità Volt-Watt",
    "lAUVoltWattDischarge": "Scaricamento modalità Volt-Watt",
    "lAUFreqIncMode": "Risposta all'incremento della frequenza",
    "lAUFreqDecMode": "Risposta alla riduzione della frequenza",
    "lAUVoltVarMode": "Modalità Volt-Var",
    "lAUPowerRateLimits": "Power rate limits",
    "lAUSoftRampUp": "Soft ramp up",
    "lAURampChangesInEnergy": "Changes in energy source operation",
    "lAUGradientInc": "Gradient Wgra+",
    "lAUGradientDec": "Gradient Wgra-",
    "lAUTargetType": "Modalità Cosphi (P)",
    "lAuLocalGridCodes": "Codice di rete locale",
    "lAUFixedFac": "Fattore di potenza fisso",
    "lAUHeader": "Parametro griglia in Australia",
    "lCosPhi1": "cosPhi at 0% power",
    "lCosPhi2a": "cosPhi at X% power",
    "lCosPhi2b": "X (%)",
    "lCosPhi3": "cosPhi at 100% power",
    "lCosPhiReg": "Attivare il controllo della potenza reattiva",
    "l4105Header": "Parametri di rete Germania",
    "lBatteryWizard": "Procedura guidata della batteria",
    "lBatteryHeader": "Procedura guidata del modulo batteria",
    "lStart": "Inizio",
    "lAbort": "Coro",
    "lBatteryFuelgauge": "Stato di carica: ",
    "lBatterySerial": "Numero di serie: ",
    "lWizardVoltage": "Tensione: ",
    "lWizardCurrent": "Corrente: ",
    "Confirm": "Confermare",
    "Restart": "Riavviare",
    "lBatteryVersion": "Versione-FW: ",
    "lWizardPackageFirstRun": "L'attivazione del pacchetto è possibile solo dopo aver riaperto la configurazione guidata, poiché la memoria SENEC deve essere prima registrata sul nostro portale.",
    "lIslandModePackage": "PACCHETTO SOFTWARE:",
    "lIslandModeStatus": "PRECONDIZIONE DEL SISTEMA:",
    "lIslandModeBattery": "BATTERIA:",
    "lEmergModeCapacity": "Capienza:",
    "BMZClose": "Terminato",
    /* VDE-AR-N4105 2019 (only applies to Germany) */
    "l4105cosphiSetting": "Individuelle Blindleistungsbereitstellung (CosPhi)",
    "l4105cosphiSettingIndividual": "Blindleistungsbereitstellung (CosPhi)",
    "l4105cosphiTimeLimit": "Zeit bis zum Erreichen der Blindleistungsvorgabe (s)",
    "l4105FRT": "Rückkehr zur erforderlichen Blindleistung nach Fehlerende (s)",
    "l4105activePowerControlOverFrequency": "Wirkleistungsanpassung bei Überfrequenz (Hz)",
    "l4105activePowerControlUnderFrequency": "Wirkleistungsanpassung bei Unterfrequenz (Hz)",
    "l4105activePowerControlDroopOverFrequency": "Statik bei Überfrequenz (%)",
    "l4105activePowerControlDroopUnderFrequency": "Statik bei Unterfrequenz (%)",
    "lPvWizardHeader": "FV impostazioni",
    "lInsulationResistance": "Resistenza di isolamento in Ohm/V",
    "lStartSelftest": "Avvio dell'autotest",
    "lPv0Label": "PV 1:",
    "lPv1Label": "PV 2:",
    "idShowButton": "indicare",
    "idHideButton": "nascondere",
    "lLicense": "LICENZE DI TERZE PARTI",
    "lTempSensorWarning": "Il controllo della temperatura minima funziona solo con i sensori di temperatura. Se nessuno è configurato, il riscaldatore non si accenderà.",
    "lWbProhibited": "Wallbox bloccato dal portale web.",
    "lStartFanTest": "Avviare il test del ventilatore",
    "lConfirmFanTest": "Conferma test del ventilatore",
    "lRotateTrigger": "Ruota Logfile",
    "lGetNspLog": "NSP Logfile"
};

var tooltip = {
    "checkboxWizardAUresponsemode_0": "Limitare la potenza di carica in base alla tensione di rete.",
    "checkboxWizardAUresponsemode_1": "Limitazione della potenza di scarica in base alla tensione di rete.",
    "checkboxWizardAUresponsemode_2": "Limitare la potenza di carica in caso di sovrafrequenza della rete.",
    "checkboxWizardAUresponsemode_3": "Limitare la potenza di scarico in caso di sovrafrequenza di rete.",
    "checkboxWizardAUresponsemode_4": "Regolare la potenza reattiva in base alla tensione di rete.",
    "GUI_DATA_BATINV1_TEMP": "Half bridge 1, half bridge 2, throttle. Se disponibile: nucleo del trasformatore, isolamento del trasformatore.",
    "GUI_DATA_BATINV2_TEMP": "Half bridge 1, half bridge 2, throttle. Se disponibile: nucleo del trasformatore, isolamento del trasformatore.",
    "GUI_DATA_BATINV3_TEMP": "Half bridge 1, half bridge 2, throttle. Se disponibile: nucleo del trasformatore, isolamento del trasformatore.",
    "WIZARDDEVICE_WALLBOX_SLAVE_ADRESS0": "Intervallo di indirizzi: 1 a 16",
    "WIZARDDEVICE_WALLBOX_SLAVE_ADRESS1": "Intervallo di indirizzi: 1 a 16",
    "WIZARDDEVICE_WALLBOX_SLAVE_ADRESS2": "Intervallo di indirizzi: 1 a 16",
    "WIZARDDEVICE_WALLBOX_SLAVE_ADRESS3": "Intervallo di indirizzi: 1 a 16",
};

var system_state_name = {
    0: "STATO INIZIALE",
    1: "ERRORE COMMUNICAZIONE INVERTER",
    2: "ERRORE WATTMETRO",
    3: "RICEVITORE RIPPLE CONTROL",
    4: "PRIMA CARICA",
    5: "CARICA DI MANTENIMENTO",
    6: "CARICA DI MANTENIMENTO COMPLETATA",
    7: "MANUTENZIONE: NECESSARIA",
    8: "CARICA DI SICUREZZA MANUALE",
    9: "CARICA DI SICUREZZA COMPLETA",
    10:"CARICA COMPLETA",
    11:"CARICA DI EQUALIZZAZIONE",
    12:"CARICA DI DESOLFATAZIONE",
    13:"ACCUMULATORE CARICO",
    14:"CARICA",
    15:"ACCUMULATORE SCARICO",
    16:"SCARICA",
    17:"FV + SCARICA",
    18:"RETE + SCARICA",
    19:"PASSIVO",
    20:"SPENTO",
    21:"AUTOCONSUMO",
    22:"RIAVVIO",
    23:"CARICA DI EQUALIZZAZIONE MANUALE",
    24:"CARICA DI DESOLFATAZIONE MANUALE",
    25:"CARICA DI SICUREZZA",
    26:"MODALITÀ PROTEZIONE ACCUMULATORE",
    27:"ERRORE EG",
    28:"EG: CARICA",
    29:"EG: SCARICA",
    30:"EG: PASSIVO",
    31:"CARICA EG PROIBITA",
    32:"SCARICAMENTO EG PROIBITO",
    33:"CARICA D'EMERGENZA",
    34:"AGGIORNAMENTO SOFTWARE",
    35:"ERRORE SPI",
    36:"ERRORE SPI: RETE ",
    37:"ERRORE SPI: HARDWARE ",
    38:"NESSUNA CONNESSIONE AL SERVER",
    39:"ERRORE BMS",
    40:"SOSTITUZIONE DEL FILTRO NECESSARIA",
    41:"BATTERIA AL LITIO SPENTA",
    42:"IN ATTESA DI SURPLUS ENERGETICO",
    43:"TEST DI CAPACITÀ: CARICA",
    44:"TEST DI CAPACITÀ: SCARICA",
    45:"CARICA DI DESOLFATAZIONE MANUALE: ATTESA",
    46:"CARICA DI DESOLFATAZIONE MANUALE: COMPLETA",
    47:"CARICA DI DESOLFATAZIONE MANUALE: ERRORE",
    48:"EQUALIZZAZIONE: ATTESA",
    49:"CARICA D'EMERGENZA: ERRORE",
    50:"EQUALIZZAZIONE MANUALE: ATTESA",
    51:"EQUALIZZAZIONE MANUALE: ERRORE",
    52:"EQUALIZZAZIONE MANUALE: COMPLETA",
    53:"CARICA DI DESOLFATAZIONE: ATTESA",
    54:"FASE FINALE CARICA",
    55:"SEZIONATORE BATTERIA OFF",
    56:"PEAK SHAVING: ATTESA",
    57:"ERRORE DISPOSITIVO DI CARICA",
    58:"ERRORE NPU",
    59:"BMS DISCONESSO",
    60:"CARICA DI MANUTENZIONE ERRORE",
    61:"CARICA DI SICUREZZA MANUALE ERRORE",
    62:"CARICA DI SICUREZZA ERRORE",
    63:"NESSUNA CONNESSIONE MASTER",
    64:"MODALITA DI PROTEZIONE LITIO ATTIVA",
    65:"MODALITA DI PROTEZIONE LITIO COMPLETA",
    66:"ERORE DI TENSIONE BATTERIA",
    67:"BMS DC SPENTO",
    68:"INIZIALIZZAZIONE DELLA RETE",
    69:"STABILIZZAZIONE DELLA RETE",
    70:"ARRESTO REMOTO",
    71:"OFFPEAK-CARICA",
    72:"ERRORE MEZZO PONTE",
    73:"BMS: ERRORE TEMPERATURA DI FUNZIONAMENTO",
    74:"FACOTRY SETTINGS NON TROVATO",
    75:"FUNZIONAMENTO ISOLATO",
    76:"FUNZIONAMENTO ISOLATO ACCUMULATORE SCARICO",
    77:"ERORE DI FUNZIONAMENTO ISOLATO",
    78:"INIZIALIZZAZIONE",
    79:"MODALITA INSTALLAZIONE",
    80:"RETE OFFLINE",
    81:"AGGIORNAMENTO BMS NECESSARIO",
    82:"CONFIGURAZIONE BMS NECESSARIA",
    83:"TEST DI ISOLAMENTO",
    84:"AUTOTEST",
    85:"CONTROLLO ESTERNO",
    86:"ERRORE SENSORE DI TEMPERATURA",
    87:"OPERATORE DI RETE: CARICA BLOCCATA",
    88:"OPERATORE DI RETE: SCARICA BLOCCATA",
    89:"CAPACITA INUTILIZZATA",
    90:"ERRORE DI AUTOTEST",
    91:"FAGLIA TERRESTRE",
};

var system_type_name =
 {
    0: "Senec Home 8.0 / piombo",
    1: "Senec Business 30.0 / piombo",
    2: "Solarinvert Storage 10.0 / litio",
    3: "Senec Home 4.0 / piombo",
    4: "Senec Home 5.0/7.5/10.0 / litio",
    5: "Senec Home 15.0 / litio",
    6: "Senec Business 25.0 / litio",
    7: "Senec Home 6.0 / piombo",
    8: "Senec Home 10.0 / piombo",
    9: "Senec Home V2 5.0/7.5/10.0 / litio",
   10: "Senec Business V2 30.0 / piombo",
   11: "Senec Home V2 10.0 / piombo",
   12: "OEM LG",
   13: "Senec Business V2_2ph / Lithium",
   14: "Senec Business V2 3ph / Lithium",
   15: "Senec Home V2.1 1ph / Lithium",
   16: "ADS Tec",
   17: "SENEC.Home V3 hybrid",
   18: "SENEC.Home V3 hybrid duo",
   19: "SENEC.Home V3 hybrid",
};

var batt_type_name = {
    0: "Studer Xtender",
    1: "SenecBatt",
    2: "Senec Inverter V2",
    3: "SENEC.Inverter V2.1",
    4: "SENEC.Inverter V3 LV"

};

var pwr_unit_type_name = {
    0: "Non definito",
    1: "Solarinvert SHKW",
    2: "SENEC.Heat"
};

var wallbox_adress_name = "Indirizzo";

var wallbox_unknown_hw_type = "sconosciuto";

var wallbox_state_name = {
    0xA1: "In attesa di collegamento ad EV",
    0xB1: "Richiesta carica da auto elettrica",
    0xB2: "L'auto elettrica è pronta per la ricarica",
    0xC2: "L'auto elettrica è in carica",
    0xC3: "Carica auto elettrica a corrente ridotta",
    0xC4: "Carica auto elettrica a corrente ridotta",
    0xE0: "Wallbox disattivato dal EN1 o aggiornamento",
    0xE1: "Test",
    0xE2: "L'unità di controllo può essere programmata",
    0xE3: "Attendere la comunicazione con il sistema di accumulo SENEC",
    0xF1: "Errore: Contatto chiuso (saldato)",
    0xF2: "Errore interno",
    0xF3: "Rilevata corrente di guasto DC",
    0xF4: "Errore connessione",
    0xF5: "Blocco della presa per la ricarica non riuscito",
    0xF6: "Guasto del cavo",
    0xF7: "Segnalazione sovratemperatura",
    0xF8: "Errore di comunicazione con l'auto elettrica",
    0xF9: "Rilevata sovracorrente",
    0xF10: "Errore: Temperature limite superate!",
    0xF11: "Errore: Contatto aperto",
    0xF12: "Reserved State",
    0xF13: "Reserved State",
};

var pwr_unit_status_enum = {
    0: "Errore sovracorrente",
    1: "Errore surriscaldamento",
    2: "Errore valore temperatura T1",
    3: "Errore valore temperatura T2",
    9: "Errore wattmetro",
    10: "Errore connessione",
    11: "Rilevamento carico fallito",
    12: "Temperatura dell'acqua troppo calda",
    13: "Errore hardware",
    14: "Errore di temperatura Hardware",
    15: "La temperatura dell'acqua troppo bassa",
    16: "Errore di conteggio dei sensori",
    17: "Spegnimento principale"
};

var enfluri_name = {
    0: "Non definito",
    1: "WATTMETRO:&nbsp;RETE",
    2: "CONSUMI&nbsp;DOMESTICI",
    3: "PRODUZIONE&nbsp;DIREZIONE&nbsp;FLUSSO:"
};

var OnOff_lang = {
    0: "Off",
    1: "On"
};

var NoneAvailable_lang = {
    0: "No",
    1: "Disponibile"
};

var feature_state = {
    0: "Chiuso",
    1: "Acquisita"
};

var condition_state = {
	0: "Non soddisfatto",
	1: "Soddisfatto"
};

var battery_state = {
	"EMPTY": "Vuoto/Offline",
	"ERROR": "Error",
	"OK": "OK"
};

var BatteryPhase = {
    0: "Nessuno",
    1: "Alimentazione costante",
    2: "Tensione costante",
    3: "Livellamento",
    4: "Fase flottante",
    5: "Fase flottante ridotta",
    6: "Tensione costante periodica"
};

var TimeZoneArray = {
	"Europe/Berlin": "Europa/Berlino",
	"Europe/Rome": "Europa/Rome",
	"Europe/Vienna": "Europa/Vienna",
	"Europe/Zurich": "Europa/Zurich",
	"Europe/Paris": "Europa/Parigi",
	"Europe/Amsterdam": "Europa/Amsterdam",
	"Europe/Brussels": "Europa/Bruxelles",
	"Australia/Perth": "Australia/Perth",
	"Australia/Darwin": "Australia/Darwin",
	"Australia/Adelaide": "Australia/Adelaide",
	"Australia/Brisbane": "Australia/Brisbane",
	"Australia/Sydney": "Australia/Sydney",
	"Australia/Hobart": "Australia/Hobart",
	"Australia/Melbourne": "Australia/Melbourne",
	"Europe/London": "Europa/London"
};

var CEI_Status = {
	0: "Tensione massima",
	1: "Tensione minima",
	2: "Temperatura",
	3: "Corrente di rete",
	4: "Carica speciale",
	8: "Avviamento CEI ",
	9: "Sovrafrequenza",
	10: "Stabilizzazione"
};

var SysUpdateState = {
	0: "Notifica al server: riavvio del sistema",
	1: "In attesa di richiesta successiva",
	2: "Notifica al server: stato",
	3: "Download del software",
	4: "Download del checksum in corso",
	5: "Controllo del checksum in corso",
	6: "Download dell’interfaccia web",
	7: "Download del checksum in corso",
	8: "Controllo del checksum ed estrazione della GUI",
	9: "Riavvia il sistema - Ricarica pagina fra 60 secondi."
};

var bms_status_enum = {
    4: "CapacityAlarm",
    5: "FullyCharged",
    6: "BatteryInstalled",
    7: "CommunicationFailure",
    8: "TerminateDischarge",
    9: "TerminateCharge",
    10: "OverDischargeAlarm",
    11: "OverChargeAlarm",
    12: "TemperatureProtectionCharge",
    13: "TemperatureProtectionDischarge",
    14: "OverCurrentCharge",
    15: "OverCurrentDischarge"
};

var CountryCodeArray = {
	"de": "Germania",
	"it": "Italia",
	"au": "Australia",
	"at": "Austria",
	"gb": "Gran Bretagna",
	"ch": "Svizzera",
	"fr": "Francia",
	"be": "Belgio",
	"nl": "Paesi Bassi"
};

var inverterNames = {
    "INV_LV": "SENEC.Home V3 LV Inverter",
    "INV_HV": "SENEC.Home V3 HV Inverter",
};

var Samsung_Wizard = {
	"confirmInternalCan": "Verificare che il cavo patch bianco sia inserito nella porta sul modulo batteria A contrassegnato in nero.",
	"clickConfirm": "Confermare la finestra di dialogo premendo \"Inizio\".",
	"scanningModules": "Ricerca modulo...",
	"detectedModuleCount": "Numero di moduli rilevati:",
	"checkModuleCount": "Verificare il numero di moduli batteria rilevati e premere \"Confermare\".",
	"noModulesDetected": "Nessun modulo rilevato!",
	"moduleCountIncorrect": "Se il numero di moduli rilevati è errato:",
	"checkWiring": "Controllare il cablaggio dei cavi patch e del cavo di riattivazione sul modulo batteria A.",
	"restartScanning": "Ripeti la scansione per i moduli batteria premendo \"Riavviare\".",
	"changeToExternalCan": "Inserire il cavo patch bianco nella porta bianca sul modulo batteria A.",
	"waitForExternalCan": "Successivamente, attendere alcuni secondi per stabilire la connessione.",
	"waitForInverter": "Avvio dell'inverter...",
	"equalCharging": "Equalizzazione dello stato di carica dei moduli batteria...",
	"testCharging": "Esecuzione della carica di prova...",
	"chargingFailed": "Carica di prova non riuscita!",
	"checkPowerPlugs": "Controllare i cavi di alimentazione.",
	"wizardDone": "Wizard completato.",
	"finishWizard": "Installazione terminata. Premere \"Terminato\" per procedere.",
	"abortWizard": "Avviso: la procedura guidata della batteria deve essere completata correttamente per completare l'installazione."
};
